In [3]:
import pandas as pd
import numpy as np

pd.set_option("display.max_colwidth", None)

In [20]:
data = pd.read_parquet('../data/data.parquet', engine='pyarrow')

data

            id                                     message_id  \
0       146989  <31789370.1075859282160.JavaMail.evans@thyme>
1       146898  <30479403.1075859280910.JavaMail.evans@thyme>
2        93788  <12502918.1075861238248.JavaMail.evans@thyme>
3        93551  <12951982.1075862555054.JavaMail.evans@thyme>
4       181661  <27286448.1075862473720.JavaMail.evans@thyme>
...        ...                                            ...
249995   18055  <23598633.1075840230833.JavaMail.evans@thyme>
249996   17547   <8676252.1075840231346.JavaMail.evans@thyme>
249997   14154   <3993748.1075848307695.JavaMail.evans@thyme>
249998   11721  <32593681.1075858079530.JavaMail.evans@thyme>
249999    8511  <24662905.1075858125856.JavaMail.evans@thyme>

                            date                            from  \
0      2020-12-29 20:53:46+00:00             jody421@hotmail.com
1      2020-12-24 23:36:06+00:00             jody421@hotmail.com
2      2012-11-28 04:47:24+00:00           dvdnow_77395@xoip.com
3      2012-11-18 16:28:05+00:00           dvdnow_52772@xoip.com
4      2004-02-04 02:41:13+00:00  hotwebcash@lists.adversend.com
...                          ...                             ...
249995 1980-01-01 00:00:00+00:00       rosalee.fleming@enron.com
249996 1980-01-01 00:00:00+00:00       rosalee.fleming@enron.com
249997 1980-01-01 00:00:00+00:00    doug.gilbert-smith@enron.com
249998 1980-01-01 00:00:00+00:00       matthew.lenhart@enron.com
249999 1980-01-01 00:00:00+00:00       matthew.lenhart@enron.com

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                to  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       [undisclosed.recipients@mailman.enron.com]
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       [undisclosed.recipients@mailman.enron.com]
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             None
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             None
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            [m..presto@enron.com]
...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ...

In [34]:
train = pd.read_parquet('../data/train.parquet', engine='pyarrow')

train.loc[50:100, ['sender', 'subject', 'body']]

                                              sender  \
50                         benjamin.rogers@enron.com
51                                 mneeley@caiso.com
52                              mary.moore@enron.com
53                                j..sturm@enron.com
54                           brown_mary_jo@lilly.com
55                             mark.breese@enron.com
56   the_economist-business-admin@news.economist.com
57                               fool@motleyfool.com
58                         mitchell.taylor@enron.com
59                              pete.davis@enron.com
60                        audrey.robertson@enron.com
61                            gerald.nemec@enron.com
62                            ben.gwaltney@enron.com
63                               p..o'neil@enron.com
64                                 40enron@enron.com
65                          juan.hernandez@enron.com
66                      kenneth.thibodeaux@enron.com
67                             kysa.alport@enron.com
68                             jose.favela@enron.com
69                             john.fiscus@enron.com
70                             frank.ermis@enron.com
71                      grcmwebmaster@mail.house.gov
72                             randall.gay@enron.com
73                               rika.imai@enron.com
74                               m..presto@enron.com
75                       debra.perlingiere@enron.com
76                      dgagliardi@reliantenergy.com
77   networkcommerce-rcfh20011213@ombramarketing.com
78                      john.postlethwaite@enron.com
79                              lisa.bills@enron.com
80                              tana.jones@enron.com
81                             steven.kean@enron.com
82                          staci.holtzman@enron.com
83                                 dkg@enernetok.com
84                                mwilczek@nyiso.com
85                             ann.ballard@enron.com
86                              tana.jones@enron.com
87                              mryantaber@nyiso.com
88                       melinda.gallishaw@enron.com
89                    scharnberger-armin@t-online.de
90                               tom.moran@enron.com
91                          robin.rodrigue@enron.com
92                              tana.jones@enron.com
93                     enron.announcements@enron.com
94                                 em418@hotmail.com
95                               ron.coker@enron.com
96                             steven.kean@enron.com
97                        maureen.mcvicker@enron.com
98                       janette.elbertson@enron.com
99                                 apapesch@isda.org
100                       arsystem@mailman.enron.com

                                                                                                       subject  \
50
51                                                                                 total transfer capabilities
52                                                                                        prayer list addition
53                                                                                power trading and heat rates
54                                                                                         lilly press release
55                                                                          ena master contracts w/ jeff hodge
56                                                       the world this week: business 5th - 11th january 2002
57                                                                      foolwatch: aol/time warner at the wire
58                                                                                                confidential
59                                                                     start date: 1/8/02; hourahead hour: 20;
60                                                                                             tw 1090 meeting
61                                                                                               colonial ca's
62                                                                                        check to be reversed
63                                                          rvms (ercot) - conf call - matt mcdonald/accenture
64                                                                                          entouch newsletter
65                                                                                   don't forget to register!
66                                               erv notification:  (violation/notification memo - 10/24/2001)
67                                                                             ees daily sheet for october 1st
68                                               - inventory collected from cn=robert benson/ou=corp/o=enron -
69                                                                                           2002 capital plan
70                                                                                                        test
71                                                                  january 15th letter from rep. henry waxman
72                                                                                           training subjects
73                                                                                          meeting - december
74                                                                                          meeting - december
75                                                                                                      sierra
76                                                                                  true orange fax/e-mail #86
77                                                            get free shipping & handling from fingerhut.com!
78                                                                           intercompany deals with insurance
79                                                                                  intergen letter agreements
80                                                                 online/net works confidentiality agreements
81                                                                              weekly retail meeting, eb 27c1
82                                                                                               csa amendment
83                                                                   bonepile: enron whggs mortg age agreement
84   price reservations 5 february 2002 real-time and hour-ahead markets, and 6 february 2002 day-ahead market
85                                                                                     potential 4(c) document
86                                                                                          peabody coal sales
87                                               nyiso market structure working group meeting, august 27, 2001
88                                                                          2/21/02-sw region director meeting
89                                                                                                    morning!
90                                                                                         eim-steel customers
91
92                                                                           credit approvals week ending 12/3
93                                                                                          enron kids' center
94                                                                                                         hi!
95                                           additional pg&e question and an aquila question - all on pastoria
96                                                                                      transatlantic meetings
97                       sanjay - meeting w/ken lay,mary joyce (tell derrick and/or rob walls if time changes)
98                                                                              ken randolph's #: 713-507-6816
99                                                                                                 kyoto snaps
100                                             request submitted: access request for lisa.guilliams@enron.com

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           body

In [13]:
train = pd.read_parquet('../data/train.parquet', engine='pyarrow')

len(train)

46240

In [ ]:
import pandas as pd
from io import StringIO

text = """0,0
1,1
2,1
3,0
4,0
5,0
6,0
7,1
8,0
9,1
10,0
11,0
12,1
13,1
14,1
15,0
16,0
17,0
18,0
19,1
20,1
21,0
22,0
23,1
24,1
25,1
26,1
27,1
28,1
29,0
30,0
31,0
32,0
33,0
34,0
35,0
36,1
37,0
38,0
39,0
40,0
41,0
42,0
43,0
44,0
45,0
46,1
47,0
48,1
49,0
50,0
51,1
52,0
53,0
54,0
55,0
56,0
57,0
58,1
59,0
60,0
61,1
62,1
63,0
64,0
65,1
66,0
67,0
68,1
69,0
70,0
71,0
72,0
73,1
74,1
75,1
76,0
77,0
78,1
79,1
80,1
81,1
82,1
83,0
84,0
85,1
86,1
87,0
88,1
89,0
90,1
91,0
92,1
93,0
94,0
95,1
96,0
97,0
98,0
99,0
100,1
"""

df = pd.read_csv(StringIO(text), names=["id", "gold_labels"])[['gold_labels']]
out = train.merge(df, left_index=True, right_index=True, how='left')[['message_id', 'gold_labels']]

out = out[out['gold_labels'].notna()]
out.to_parquet('../data/gold_labels.parquet', engine='pyarrow', index=False)

In [36]:
out

                                        message_id  gold_label
0    <10244403.1075858337084.JavaMail.evans@thyme>         0.0
1    <11418771.1075852854402.JavaMail.evans@thyme>         1.0
2    <12340626.1075842620743.JavaMail.evans@thyme>         1.0
3    <14093098.1075855280647.JavaMail.evans@thyme>         0.0
4    <31489162.1075858390575.JavaMail.evans@thyme>         0.0
..                                             ...         ...
96   <14909201.1075858883867.JavaMail.evans@thyme>         0.0
97   <22083454.1075847947537.JavaMail.evans@thyme>         0.0
98   <12256968.1075861947398.JavaMail.evans@thyme>         0.0
99   <21543202.1075845031894.JavaMail.evans@thyme>         0.0
100  <26465506.1075855081831.JavaMail.evans@thyme>         1.0

[101 rows x 2 columns]

In [15]:
test = pd.read_parquet('../data/test.parquet', engine='pyarrow')
len(test)

11561

In [73]:
train.columns

Index(['id', 'message_id', 'date', 'sender', 'to', 'cc', 'bcc', 'subject',
       'body', 'x_from', 'x_to', 'x_cc', 'x_bcc', 'x_folder', 'x_origin',
       'x_filename', 'source_file', 'thread_id', 'parent_id', 'sequence',
       'is_forward', 'is_reply', 'sender_domain', 'recipient_domain'],
      dtype='str')

In [ ]:
data['unique_id'] = data['from'].astype(str) + data['subject'].astype(str) + data['date'].astype(str)

data.groupby('unique_id')['x_folder'].nunique() > 1

unique_id
'todd'.delahoussaye@enron.comFW: lists2002-02-01 16:18:12+00:00                                    False
'todd'.delahoussaye@enron.comTD+1, 10-24-012001-10-24 13:50:26+00:00                               False
'todd'.delahoussaye@enron.comTD+1, 11-20-012001-11-20 16:01:44+00:00                               False
'todd'.delahoussaye@enron.comTD+1, 11-21-012001-11-21 16:41:36+00:00                               False
--migrated--dodle@ercot.comChange Controls/Questions for 10/31/01 call2001-10-29 20:23:52+00:00    False
                                                                                                   ...
zwharton@dawray.comRE: car2001-09-07 13:51:24+00:00                                                False
zwharton@dawray.comRE:2001-10-22 16:34:24+00:00                                                    False
zwharton@dawray.comRE:2001-10-24 15:44:00+00:00                                                    False
zwharton@dawray.comRE:2001-11-26 20:06:42+00:00                                                    False
zwharton@dawray.comRobert and the grout2001-10-23 15:17:30+00:00                                   False
Name: x_folder, Length: 123332, dtype: bool

In [49]:
data[data['unique_id'] == 'zwharton@dawray.comRE: PHOEBE MCVAY E-TICKET ITINERARY2000-11-09 10:51:00+00:00']

           id                                    message_id  \
181129  61038  <7809108.1075858072562.JavaMail.evans@thyme>
181130  60701  <6117806.1075858076840.JavaMail.evans@thyme>
181131  60175  <5311729.1075858078376.JavaMail.evans@thyme>

                            date                 from  \
181129 2000-11-09 10:51:00+00:00  zwharton@dawray.com
181130 2000-11-09 10:51:00+00:00  zwharton@dawray.com
181131 2000-11-09 10:51:00+00:00  zwharton@dawray.com

                               to    cc   bcc  \
181129  [martin.cuilla@enron.com]  None  None
181130  [martin.cuilla@enron.com]  None  None
181131  [martin.cuilla@enron.com]  None  None

                                    subject  \
181129  RE: PHOEBE MCVAY E-TICKET ITINERARY
181130  RE: PHOEBE MCVAY E-TICKET ITINERARY
181131  RE: PHOEBE MCVAY E-TICKET ITINERARY

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     body  \
181129   Thanks sweets!\n\n-----Original Message-----\nFrom: Martin.Cuilla@enron.com [mailto:Martin.Cuilla@enron.com]\nSent: Thursday, November 09, 2000 10:48 AM\nTo: zwharton@dawray.com\nSubject: RE: PHOEBE MCVAY E-TICKET ITINERARY\n\n\n\n---------------------- Forwarded by Martin Cuilla/HOU/ECT on 11/09/2000\n10:47 AM ---------------------------\n\n\n (Embedded     Enron North America Corp.\n image moved\n to file:      From:  Airam Arteaga\n pic22929.pcx) 11/09/2000 11:47 AM\n\n\n\n\n\n\nTo:   Martin Cuilla/HOU/ECT@ECT\ncc:\nSubject:  RE: PHOEBE MCVAY E-TICKET ITINERARY\n\n\n---------------------- Forwarded by Airam Arteaga/HOU/ECT on 11/09/2000\n10:45 AM ---------------------------\n\n\nMadeleine Cardoso <madeleine.cardoso@travelpark.com> on 11/09/2000 10:44:34\nAM\n\nTo:   "'airam.arteaga@enron.com'" <airam.arteaga@enron.com>\ncc:\nSubject:  RE: PHOEBE MCVAY E-TICKET ITINERARY\n\n\n                                                   SALES AGT: MC/ZX6ROG\n\n                                          MCVAY/PHOEBE\n                                          EB\n                                          E-TKT RECEIPT\n  ENRON CORP\n\n\n\n\n\n  DATE:  NOV 09 2000\n\nSERVICE               DATE  FROM           TO             DEPART  ARRIVE\n\nCONTINENTAL AIRLINES  01DEC AUSTIN TX      HOUSTON TX     1120A   1216P\nCO 1750    T          FRI   BERGSTROM INTL G.BUSH INTERCO\n                                           TERMINAL C\n                                                          NON STOP\n                            RESERVATION CONFIRMED         0:56 DURATION\n                  AIRCRAFT: MCDONNELL DOUGLAS ALL MD-80 SERIES\n                            SEAT 19F NO SMOKING CONFIRMED MCVAY/PHOEBE(ID\n\nCONTINENTAL AIRLINES  01DEC HOUSTON TX     NEW YORK NY    115P    547P\nCO 1970    Q          FRI   G.BUSH INTERCO LA GUARDIA\n                            TERMINAL C     TERMINAL M\n                            SNACK                         NON STOP\n                            RESERVATION CONFIRMED         3:32 DURATION\n                  AIRCRAFT: BOEING 737-300\n                            SEAT 16F NO SMOKING CONFIRMED MCVAY/PHOEBE(ID\n\nCONTINENTAL AIRLINES  03DEC NEW YORK NY    CLEVELAND OH   120P    259P\nCO 1905    Q          SUN   LA GUARDIA     HOPKINS INT\n                            TERMINAL M\n                                                          NON STOP\n                            RESERVATION CONFIRMED         1:39 DURATION\n                  AIRCRAFT: BOEING 737-300\n                            SEAT 19A NO SMOKING CONFIRMED MCVAY/PHOEBE(ID\n\nCONTINENTAL AIRLINES  03DEC CLEVELAND OH   HOUSTON TX     405P    605P\nCO 1999    Q          SUN   HOPKINS INT    G.BUSH INTERCO\n                                           TERMINAL C\n                            SNACK                         NON STOP\n                            RESERVATION CONFIRMED         3:00 DURATION\n                  AIRCRAFT: MCDONNELL DOUGLAS ALL MD-80 SERIES\n                            SEAT 19A NO SMOKING CONFIRMED MCVAY/PHOEBE(ID\n\nCONTINENTAL AIRLINES  03DEC HOUSTON TX     AUSTIN TX      825P    922P\nCO 1507    T          SUN   G.BUSH INTERCO BERGSTROM INTL\n                            TERMINAL C\n                                                          NON STOP\n                            RESERVATION CONFIRMED         0:57 DURATION\n                  AIRCRAFT: BOEING 757-200/300\n                            SEAT 26C NO SMOKING CONFIRMED MCVAY/PHOEBE(ID\n               THIS IS A NON-REFUNDABLE FARE THAT REQUIRES\n               TRAVEL ON THESE SPECIFIC DATES AND FLIGHTS.\n               ANY CHANGES WILL RESULT IN A PENALTY AND/OR\n                         ADDITIONAL COLLECTION.\n           **************************************************\n         YOUR TICKET REFLECTS A NEGOTIATED DISCOUNT FROM THE TAP\n              THE PUBLISHED FARE FOR THIS TICKET IS $302.00\n           **************************************************\n\nMISCELLANEOUS         02APR HOUSTON TX\n                      MON   ** THANK YOU FOR USING THE TAP **\n\n\nRESERVATION NUMBER(S)  CO/NK0Z1D\n\nMCVAY/PHOEBE  S5C0413R1058               TICKET:CO/ETKT 005 7017929690-91\n\nROUND TRIP AIRFARE...$253.37\n*******************************************\nINTL TVLRS: CARRY SOS WALLET CARD W/ENRONASSISTANCE INFO\nCALL SOS MEDICAL EMERGENCY:IN U.S 800 523-6586\nCALL SOS MEDICAL EMERGENCY:INTL 215 245-4707 (COLLECT)\n*********************************************\nTHIS IS THE PASSENGER RECEIPT FOR YOUR ELECTRONIC TICKET.\nPLEASE CHECK-IN WITH PHOTO IDENTIFICATION AND WITH\nEITHER (1) THIS RECEIPT OR (2) YOUR CONFIRMATION NUMBER.\nYOUR E-TKT CONFIRMATION NUMBER IS: N K 0 Z 1 D\n******************************************\nE-TICKET 005-7017929690-91 ISSUED 09NOV00 - $253.37.\n\n
181130   Thanks sweets!\n\n-----Original Message-----\nFrom: Martin.Cuilla@enron.com [mailto:Martin.Cuilla@enron.com]\nSent: Thursday, November 09, 2000 10:48 AM\nTo: zwharton@dawray.com\nSubject: RE: PHOEBE MCVAY E-TICKET ITINERARY\n\n\n\n---------------------- Forwarded by Martin Cuilla/HOU/ECT on 11/09/2000\n10:47 AM ---------------------------\n\n\n (Embedded     Enron North America Corp.\n image moved\n to file:      From:  Airam Arteaga\n pic22929.pcx) 11/09/2000 11:47 AM\n\n\n\n\n\n\nTo:   Martin Cuilla/HOU/ECT@ECT\ncc:\nSubject:  RE: PHOEBE MCVAY E-TICKET ITINERARY\n\n\n---------------------- Forwarded by Airam Arteaga/HOU/ECT on 11/09/2000\n10:45 AM ---------------------------\n\n\nMadeleine Cardoso <madeleine.cardoso@travelpark.com> on 11/09/2000 10:44:34\nAM\n\nTo:   "'airam.arteaga@enron.com'" <airam.arteaga@enron.com>\ncc:\nSubject:  RE: PHOEBE MCVAY E-TICKET ITINERARY\n\n\n                                                   SALES AGT: MC/ZX6ROG\n\n                                          MCVAY/PHOEBE\n                                          EB\n                                          E-TKT RECEIPT\n  ENRON CORP\n\n\n\n\n\n  DATE:  NOV 09 2000\n\nSERVICE               DATE  FROM           TO             DEPART  ARRIVE\n\nCONTINENTAL AIRLINES  01DEC AUSTIN TX      HOUSTON TX     1120A   1216P\nCO 1750    T          FRI   BERGSTROM INTL G.BUSH INTERCO\n                                           TERMINAL C\n                                                          NON STOP\n                            RESERVATION CONFIRMED         0:56 DURATION\n                  AIRCRAFT: MCDONNELL DOUGLAS ALL MD-80 SERIES\n                            SEAT 19F NO SMOKING CONFIRMED MCVAY/PHOEBE(ID\n\nCONTINENTAL AIRLINES  01DEC HOUSTON TX     NEW YORK NY    115P    547P\nCO 1970    Q          FRI   G.BUSH INTERCO LA GUARDIA\n                            TERMINAL C     TERMINAL M\n                            SNACK                         NON STOP\n                            RESERVATION CONFIRMED         3:32 DURATION\n                  AIRCRAFT: BOEING 737-300\n                            SEAT 16F NO SMOKING CONFIRMED MCVAY/PHOEBE(ID\n\nCONTINENTAL AIRLINES  03DEC NEW YORK NY    CLEVELAND OH   120P    259P\nCO 1905    Q          SUN   LA GUARDIA     HOPKINS INT\n                            TERMINAL M\n                                                          NON STOP\n                            RESERVATION CONFIRMED         1:39 DURATION\n                  AIRCRAFT: BOEING 737-300\n                            SEAT 19A NO SMOKING CONFIRMED MCVAY/PHOEBE(ID\n\nCONTINENTAL AIRLINES  03DEC CLEVELAND OH   HOUSTON TX     405P    605P\nCO 1999    Q          SUN   HOPKINS INT    G.BUSH INTERCO\n                                           TERMINAL C\n                            SNACK                         NON STOP\n                            RESERVATION CONFIRMED         3:00 DURATION\n                  AIRCRAFT: MCDONNELL DOUGLAS ALL MD-80 SERIES\n                            SEAT 19A NO SMOKING CONFIRMED MCVAY/PHOEBE(ID\n\nCONTINENTAL AIRLINES  03DEC HOUSTON TX     AUSTIN TX      825P    922P\nCO 1507    T          SUN   G.BUSH INTERCO BERGSTROM INTL\n                            TERMINAL C\n                                                          NON STOP\n                            RESERVATION CONFIRMED         0:57 DURATION\n                  AIRCRAFT: BOEING 757-200/300\n                            SEAT 26C NO SMOKING CONFIRMED MCVAY/PHOEBE(ID\n               THIS IS A NON-REFUNDABLE FARE THAT REQUIRES\n               TRAVEL ON THESE SPECIFIC DATES AND FLIGHTS.\n               ANY CHANGES WILL RESULT IN A PENALTY AND/OR\n                         ADDITIONAL COLLECTION.\n           **************************************************\n         YOUR TICKET REFLECTS A NEGOTIATED DISCOUNT FROM THE TAP\n              THE PUBLISHED FARE FOR THIS TICKET IS $302.00\n           **************************************************\n\nMISCELLANEOUS         02APR HOUSTON TX\n                      MON   ** THANK YOU FOR USING THE TAP **\n\n\nRESERVATION NUMBER(S)  CO/NK0Z1D\n\nMCVAY/PHOEBE  S5C0413R1058               TICKET:CO/ETKT 005 7017929690-91\n\nROUND TRIP AIRFARE...$253.37\n*******************************************\nINTL TVLRS: CARRY SOS WALLET CARD W/ENRONASSISTANCE INFO\nCALL SOS MEDICAL EMERGENCY:IN U.S 800 523-6586\nCALL SOS MEDICAL EMERGENCY:INTL 215 245-4707 (COLLECT)\n*********************************************\nTHIS IS THE PASSENGER RECEIPT FOR YOUR ELECTRONIC TICKET.\nPLEASE CHECK-IN WITH PHOTO IDENTIFICATION AND WITH\nEITHER (1) THIS RECEIPT OR (2) YOUR CONFIRMATION NUMBER.\nYOUR E-TKT CONFIRMATION NUMBER IS: N K 0 Z 1 D\n******************************************\nE-TICKET 005-7017929690-91 ISSUED 09NOV00 - $253.37.\n\n

In [45]:
dupes = data[data.duplicated(subset=['x_folder', 'unique_id'], keep=False)]
dupes.groupby('x_folder').size().sort_values(ascending=False)

x_folder
\Kay_Mann_June2001_1\Notes Folders\All documents         2782
\Kay_Mann_June2001_3\Notes Folders\Sent                  2329
\Kay_Mann_June2001_4\Notes Folders\'sent mail            2158
\Kay_Mann_June2001_2\Notes Folders\Discussion threads    1730
\Tanya_Jones_Dec2000\Notes Folders\All documents         1550
                                                         ...
\Bradley_McKay_Dec2000\Notes Folders\Sent                   2
\Bradley_McKay_Jan2002_1\Mckay, Brad\Inbox                  2
\Bradley_McKay_Jan2002_1\Mckay, Brad\Sent Items             2
\TGEACCO (Non-Privileged)\Geaccone, Tracy\CFP               2
\TGEACCO (Non-Privileged)\Geaccone, Tracy\DATEK             2
Length: 1118, dtype: int64

In [5]:
train = pd.read_parquet('../data/train.parquet', engine='pyarrow')
train

,id,message_id,date,sender,to,cc,bcc,subject,body,x_from,...,x_origin,x_filename,source_file,thread_id,parent_id,sequence,is_forward,is_reply,sender_domain,recipient_domain
0,199089,<24861977.1075858950944.JavaMail.evans@thyme>,2001-09-25 18:08:56+00:00,,[michael.bridges@enron.com],"[c..koehler@enron.com, tana.jones@enron.com]","[c..koehler@enron.com, tana.jones@enron.com]",deloitte agreement,"Michael -\n\nI have attached below a revised version of the Channel Marketing Agreement with Deloitte. This document is the most current form of agreement that needs to be used for these deals and also reflects my comments. These comments are based upon the comments submitted by Deloitte. I have incorporated those that we discussed and made some additional comments. You will note that in the ""Fee Payment"" section, I have included the present value concept that you requested. I have not, however, defined this concept, but would assert that it should be defined in the agreement. Accordingly, please let me know how you want to define it.\n\nAs I indicated above, this is a bit of a different form than the one you submitted to Deloitte for review. So that we can ensure that accurate documents are distributed, please allow us to prepare the drafts for distribution to potential channel marketing partners. Like the preparation of NDA's, this will enable the Legal Dept. to keep track of the agreement and ensure the right version is used.\n\nPlease let me know if you should need anything further.\n\nMark\n\n\n","Greenberg, Mark </O=ENRON/OU=NA/CN=RECIPIENTS/CN=MGREENBE>",...,Jones-T,TJONES (Non-Privileged).pst,data/extracted/maildir/jones-t/inbox/102.,00010e28ea14990d1df8a1c9399506b429f0f8f2de3a109603e91556fef2fb37,NaN,1,False,False,None,[enron.com]
1,189347,<18337390.1075858219287.JavaMail.evans@thyme>,2000-12-04 15:16:00+00:00,,"[kam.keiser@enron.com, phillip.love@enron.com]",None,None,enron canada 08/00 ontario variances,"Phillip and Kam\n\nI put together spreadsheets summarizing the variances for Enron Canada \npurchases and sales for the Ontario region for August and it looks like we \nhave a similar situation to July in that there are two liquidations on the \npurchase side that don't reference any particular Sitara deal that are \ndirectly offset in the liquidations for Transcanada Pipeline sales. If we \nnet these two liquidations, it significantly reduces both variances. The \nTaggs are N63076.8 and 2 and N63076.C and 6. \n\n\n\nThanks,\nCathy",Cathy Sprowls,...,Love-P,plove.nsf,data/extracted/maildir/love-p/all_documents/88.,00023f219ad5a4f69d7a935d5d27b0ca9fc22b80a707f15ca1b0fe493639774f,NaN,1,False,False,None,[enron.com]
2,185978,<28674630.1075858232887.JavaMail.evans@thyme>,2000-12-04 15:16:00+00:00,,"[kam.keiser@enron.com, phillip.love@enron.com]",None,None,enron canada 08/00 ontario variances,"Phillip and Kam\n\nI put together spreadsheets summarizing the variances for Enron Canada \npurchases and sales for the Ontario region for August and it looks like we \nhave a similar situation to July in that there are two liquidations on the \npurchase side that don't reference any particular Sitara deal that are \ndirectly offset in the liquidations for Transcanada Pipeline sales. If we \nnet these two liquidations, it significantly reduces both variances. The \nTaggs are N63076.8 and 2 and N63076.C and 6. \n\n\n\nThanks,\nCathy",Cathy Sprowls,...,Love-P,plove.nsf,data/extracted/maildir/love-p/discussion_threads/249.,00023f219ad5a4f69d7a935d5d27b0ca9fc22b80a707f15ca1b0fe493639774f,<18337390.1075858219287.JavaMail.evans@thyme>,2,False,False,None,[enron.com]
3,184641,<29107275.1075858234356.JavaMail.evans@thyme>,2000-12-04 15:16:00+00:00,,"[kam.keiser@enron.com, phillip.love@enron.com]",None,None,enron canada 08/00 ontario variances,"Phillip and Kam\n\nI put together spreadsheets summarizing the variances for Enron Canada \npurchases and sales for the Ontario region for August and it looks like we \nhave a similar situation to July in that there are two liquidations on the \npurchase side that don't reference any particular Sitara deal that are \ndirectly offset in the liquidations for Transcanada Pipeline sales. If we \nnet these two liquidations, it significantly reduces both variances. The \nTaggs are N63076.8 and 2 and N63076.C and 6. \n\n\n\nThanks,\nCathy",Cathy Sprowls,...,Love-P,plove.nsf,data/extracted/maildir/love-p/notes_inbox/17.,00023f219ad5a4f69d7a935d5d27b0ca9fc22b80a707f15ca1b0fe493639774f,<28674630.1075858232887.JavaMail.evans@thyme>,3,False,False,None,[enron.com]
4,110808,<13593582.1075852616074.JavaMail.evans@thyme>,2001-10-23 08:00:34+00:00,,[jeff.king@enron.com],None,None,tgif marketplace meditation -- horizontal versus vertical,"If you are looking to feed and challenge your faith, visit\nCrosswalk.com's Spiritual Life Channel at:\nhttp://spiritual.crosswalk.com\n-----------\nT O D A Y G O D I S F I R S T\n Marketplace Meditations\n by Os Hillman\n\nHorizontal Versus Vertical\n\nGlancing this way and that and seeing no one, he killed the\nEgyptian and hid him in the sand.\n- (Exodus 2:12)\n\n\nMoses saw the pain of his people. He saw the bondage and the\ninjustice. His heart was enraged, and he decided he would do\nsomething. He would take matters into his own hands. The result\nwas murder. The motive was right, but the action was wrong. He\nwent horizontal instead of vertical with God. The action was\nwrong. Moses fled to the desert, where God prepared the man who\nwould ultimately be the deliverer of a nation. But it took 40\nyears of preparation before God determined Moses was ready. He\nwas a professional businessman-a sheepherder. It was during the\nmundane activity of work that God called on him to be a\ndeliverer.\n\nMoses was like a lot of enthusiastic Christian businesspeople who\nseek to solve a spiritual problem with a fleshly answer. The\ngreatest danger to the Christian businessperson is his greatest\nstrength-his business acumen and expertise to get things done.\nThis self-reliance can become our greatest weakness when it comes\nto moving in the spiritual realm. We're taught to be problem\nsolvers. But, like Moses, if our enthusiasm and passion are not\nharnessed by the power of the Holy Spirit, we will fail\nmiserably. Peter had to learn this lesson too. His enthusiasm got\nhim into a lot of trouble. But God was patient, just as He is\npatient with each of us. Sometimes He must put us in the desert\nfor a time in order to season us so that Christ is allowed to\nreign supreme in the process.\n\nBefore you act, pray and seek the mind of Christ until you know\nit is God behind the action. Check it out with others. You may\nsave yourself a trip to the desert.\n\nPublished and distributed by Crosswalk.com, this daily devotional is\nwritten by Os Hillman (os@marketplaceleaders.org). Os is president of\nMarketplace Leaders, an Atlanta based ministry teaching Biblical\nprinciples for career and business success. He offers a FREE newsletter\nand other resources at:\nhttp://www.marketplaceleaders.org\n\nOrder ""TGIF: Today God I s First"" - 365 daily meditations to motivate\nand inspire for $17 for TGIF subscribers. Click here to order:\n\nhttp://www.marketplaceleaders.org/displayroom/skudetail.nhtml?uid=10055\n\nTo support Os Hillman & Marketplace Leaders , click:\n https://nhf.org/applications/donate.htm?FDN=Marketplace%2BLeaders\n\nMail: 3520 Habersham Club Drive, Cumming, Georgia 30041 USA.\n\n\n____________________SUBSCRIPTION INFO_______________________\n\n* You subscribed to Marketplace Meditations as:\n < jeff.king@enron.com >\n* To unsubscribe from this newsletter immediately, click here:\n < http://link.crosswalk.com/UM/U.ASP?A3.12.261895 >\n If that link is not clickable, simply copy and paste it into\n your browser window.\n* To change your address: unsubscribe your old address\n and then subscribe your new address.\n* To subscribe, send an email to:\n < SUBSCRIBE-marketplace@lists.crosswalk.com > or go to\n < http://www.crosswalk.com/lists > for a complete list of\n our newsletters.\n* Copyright ? 2001 Crosswalk.com, Inc. and its Content\n Providers. All rights reserved.\n\n____________________________________________________________\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n","""Crosswalk.com"" <marketplace@lists.crosswalk.com>@ENRON",...,Shankman-J,JSHANKM (Non-Privileged).pst,data/extracted/maildir/king-j/deleted_items/228.,0005d17749bbd8afe4d563cf9e0c8e317d419467e95edcf13efa1b350e2dc794,NaN,1,False,False,None,[enron.com]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,127213,<5271745.1075858576207.JavaMail.evans@thyme>,2001-07-05 15:58:30+00:00,,"[gerald.nemec@enron.com, t..zivley@enron.com]",[ellen.wallumrod@enron.com],[ellen.wallumrod@enron.com],eex confirm,"Gerald,\n\nWill you please make the pricing change when you are reviewing the confirm?\n\nThanks,\nJudy\n\n -----Original Message-----\nFrom: \tZivley, Jill T. \nSent:\tThursday, July 05, 2001 10:44 AM\nTo:\tThorne, Judy; Nemec, Gerald\nCc:\tWallumrod, Ellen\nSubject:\tRE: EEX Confirm\n\nJudy, the confirm language looks good, but the price is wrong - should be Index less .0175 for the first 1700/d and Gas Daily flat for gas over that amount each month. We can put a MDQ if you want to...but the only way we would have more gas is if they add another well and we could reject it I think if we wanted to based on it not being w/in the dedication......Do you want to talk more about that? Thanks.\n\n -----Original Message-----\nFrom: \tThorne, Judy \nSent:\tThursday, July 05, 2001 9:22 AM\nTo:\tNemec, Gerald\nCc:\tZivley, Jill T.; Wallumrod, Ellen\nSubject:\tRE: EEX Confirm\nImportance:\tHigh\n\nGerald,\n\nPlease review the attached completed confirmation for EEX E&P and forward to Ellen Wallumrod to send to the customer if you approve. We need to get this to the customer today if at all possible.\n\nPer Jill Zivley, there is not an MDQ, but she will work with the customer on a monthly basis for volumes above 1700. Please let me know if we need to adjust the confirm based on that information.\n\nThanks,\nJudy Thorne\n\n << File: EEXEPconfirm.doc >> << File: enaupstreamGTC.doc >> \n -----Original Message-----\nFrom: \tNemec, Gerald \nSent:\tFriday, June 29, 2001 4:12 PM\nTo:\tThorne, Judy\nSubject:\tEEX Confirm\n\nJudy, Attached is the draft confirm for EEX. Can you fill in all the notice information for EEX. Also as we discussed, we also need to insert the well/field/lease data. Note that there is no MDQ. From the printout, it looked as though all volumes in excess of 1700 MMBtu per day were priced as gas daily. If there is an MDQ, we will need to insert it. Thanks.\n\n << File: EEXE&Pconfirm.doc >> << File: enaupstreamGTC.doc >>","Thorne, Judy </O=ENRON/OU=NA/CN=RECIPIENTS/CN=JTHORNE>",...,Nemec-G,"Nemec, Gerald (Non-Privileged).pst",data/extracted/maildir/nemec-g/inbox/939.,de41a64787c6d4ca1d4cf19e1236eae6ed3dd1bd9f9bfb0a4575f57ec36f8880,<19602187.1075858576160.JavaMail.evans@thyme>,4,False,True,None,[enron.com]
199996,127866,<16212485.1075858555027.JavaMail.evans@thyme>,2001-07-09 15:13:40+00:00,,[ellen.wallumrod@enron.com],[judy.thorne@enron.com],[judy.thorne@enron.com],eex confirm,"Attached for your further handling is the confirm and GTC for the EEX E&P Company purchase by ENA Upstream. Note that we need to have them sign the confirm, so we will need two executed originals. Let me know if you have any questions.\n\n \n","Nemec, Gerald </O=ENRON/OU=NA/CN=RECIPIENTS/CN=GNEMEC>",...,Nemec-G,"Nemec, Gerald (Non-Privileged).pst",data/extracted/maildir/nemec-g/sent_items/399.,de41a64787c6d4ca1d4cf19e1236eae6ed3dd1bd9f9bfb0a4575f57ec36f8880,<5271745.1075858576207.JavaMail.evans@thyme>,5,False,False,None,[enron.com]
199997,240346,<32606924.1075845651223.JavaMail.evans@thyme>,2001-01-08 18:15:00+00:00,,[kathleen.carnahan@enron.com],None,None,nrg ca,"Is the notice the only change? If so, it looks ok to me.",Kay Mann,...,MANN-K,kmann.nsf,data/extracted/maildir/mann-k/all_documents/3069.,de42b87c15ba5107c9cda0c44864a3a56239d1d45a029335ad2d0e6264149cd4,NaN,1,False,True,None,[enron.com]
199998,236264,<2736184.1075846078767.JavaMail.evans@thyme>,2001-01-08 18:15:00+00:00,,[kathleen.carnahan@enron.com],None,None,nrg ca,"Is the notice the only change? If so, it looks ok to me.",Kay Mann,...,MANN-K,kmann.nsf,data/extracted/maildir/mann-k/_sent_mail/2078.,de42b87c15ba5107c9cda0c44864a3a56239d1d45a029335ad2d0e6264149cd4,<32606924.1075845651223.JavaMail.evans@thyme>,2,False,True,None,[enron.com]
199999,235190,<1520075.1075845974653.JavaMail.evans@thyme>,2001-01-08 18:15:00+00:00,,[kathleen.carnahan@enron.com],None,None,nrg ca,"Is the notice the only change? If so, it looks ok to me.",Kay Mann,...,MANN-K,kmann.nsf,data/extracted/maildir/mann-k/sent/2306.,de42b87c15ba5107c9cda0c44864a3a56239d1d45a029335ad2d0e6264149cd4,<2736184.1075846078767.JavaMail.evans@thyme>,3,False,True,None,[enron.com]

In [8]:
df = pd.read_parquet('../data/dataset.parquet', engine='pyarrow')

df

,id,message_id,date,sender,to,cc,bcc,subject,body,x_from,...,sent_hour,sent_weekday,is_after_hours,is_weekend,n_recipient,n_recipient_domains,n_words,n_sentences,is_internal,is_external
0,889ca4a4bfbe6f8269b26b649d900562a2abd15c2508c6bf7e9b7d4012034cb7,<24861977.1075858950944.JavaMail.evans@thyme>,2001-09-25 18:08:56+00:00,mark.greenberg@enron.com,[michael.bridges@enron.com],"[c..koehler@enron.com, tana.jones@enron.com]","[c..koehler@enron.com, tana.jones@enron.com]",deloitte agreement,"Deloitte Agreement Michael I have attached below a revised version of the Channel Marketing Agreement with Deloitte. This document is the most current form of agreement that needs to be used for these deals and also reflects my comments. These comments are based upon the comments submitted by Deloitte. I have incorporated those that we discussed and made some additional comments. You will note that in the ""Fee Payment"" section, I have included the present value concept that you requested. I have not, however, defined this concept, but would assert that it should be defined in the agreement. Accordingly, please let me know how you want to define it. As I indicated above, this is a bit of a different form than the one you submitted to Deloitte for review. So that we can ensure that accurate documents are distributed, please allow us to prepare the drafts for distribution to potential channel marketing partners. Like the preparation of NDA's, this will enable the Legal Dept. to keep track of the agreement and ensure the right version is used. Please let me know if you should need anything further. Mark","Greenberg, Mark </O=ENRON/OU=NA/CN=RECIPIENTS/CN=MGREENBE>",...,18,1,True,False,3,1,189,12,True,False
1,4ad8b7360da6721377f00f7ed69e66a02a1f06460d97664634f7c01ff6bdec61,<33442183.1075844794684.JavaMail.evans@thyme>,2001-05-11 11:38:00+00:00,mary.cook@enron.com,[sara.shackleton@enron.com],"[gordon.mckillop@enron.com, joel.ephross@enron.com, maricela.trevino@enron.com]","[gordon.mckillop@enron.com, joel.ephross@enron.com, maricela.trevino@enron.com]",raptor and the south american swap,"Raptor and the South American Swap Maricela has requested a copy of the termination notice for the referenced swap. I advised her that you would have done the document in relation to the swap (of which I think there was only one). I cannot remember if it was ever terminated. Can you coordinate this matter with Maricela. I am covering the rest of the Raptor requests. Cordially, Mary Cook Enron North America Corp. 1400 Smith, 38th Floor, Legal Houston, Texas 77002-7361 (713) 345-7732 (phone) (713) 646-3490 (fax) mary.cook@enron.com",Mary Cook,...,11,4,True,False,4,1,88,8,True,False
2,53eb6faafab020188fdfe4bb8870b281604f3b8aaa7e6ad07d2a0023a5dca02f,<7294597.1075844926117.JavaMail.evans@thyme>,2001-05-14 13:33:00+00:00,sara.shackleton@enron.com,[mary.cook@enron.com],None,None,raptor and the south american swap,"Mary: Remember, this is the swap that you finally decided to go ahead and terminate yourself. There was much confusion about how many S.A. swaps actually exsited (only one) and after sorting through the mess, when I asked if you had estabished a Raptor ""format for termination"", you decided to do the drafting. Let me know if there is a problem. Sara Shackleton Enron North America Corp. 1400 Smith Street, EB 3801a Houston, Texas 77002 713-853-5620 (phone) 713-646-3490 (fax) sara.shackleton@enron.com Forwarded by Sara Shackleton/HOU/ECT on 05/14/2001 01:31 PM Mary Cook 05/11/2001 11:38 AM",Sara Shackleton,...,13,0,True,False,2,1,93,8,True,False
3,115a2c7a146730ed9610a46f081e6286abaa9d1fc9acd9107991b34c4f7b5862,<29107275.1075858234356.JavaMail.evans@thyme>,2000-12-04 15:16:00+00:00,cathy.sprowls@enron.com,"[kam.keiser@enron.com, phillip.love@enron.com]",None,None,enron canada 08/00 ontario variances,"Enron Canada 08/00 Ontario variances Phillip and Kam I put together spreadsheets summarizing the variances for Enron Canada purchases and sales for the Ontario region for August and it looks like we have a similar situation to July in that there are two liquidations on the purchase side that don't reference any particular Sitara deal that are directly offset in the liquidations for Transcanada Pipeline sales. If we net these two liquidations, it significantly reduces both variances. The Taggs are N63076.8 and 2 and N63076.C and 6. Thanks, Cathy",Cathy Sprowls,...,15,0,True,False,3,1,89,5,True,False
4,e16d4c4088f9c377dcd04b271edd4032ab3d57de4b4c52ab486c6a09026dfa01,<1161169.1075857401320.JavaMail.evans@thyme>,2001-03-01 10:42:00+00:00,errol.mclaughlin@enron.com,[sherry.dawson@enron.com],None,None,tenaska iii energy partners,"Tenaska III Energy Partners Please run a Mark to Market as of 12/31/2001 for TENASKA III Texas Partners. Please fax Sheila Trueblood at 402-691-9552 when you have printed the report. Thanks, Errol",Errol McLaughlin,...,10,3,True,False,2,1,32,2,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199154,a2ec42786b29dbaeb5d187f21c815ca37604aba18c775a238902de41aff6f404,<2730447.1075852338593.JavaMail.evans@thyme>,2001-10-01 22:23:35+00:00,m..taylor@enron.com,None,None,None,briefing @ enron office - re: economic stimulus pkg,"Briefing Enron Office RE: Economic Stimulus Pkg Participants: Linda Robertson, Chris Long Ed Coats","Taylor, Liz M. </O=ENRON/OU=NA/CN=RECIPIENTS/CN=LTAYLOR>",...,22,0,True,False,1,0,14,0,False,False
199155,f5a6ed418bd7bd38a165563bca51a8b6f41460b0a722a32da51c46466ae25b19,<15274191.1075843760288.JavaMail.evans@thyme>,2001-01-15 14:11:00+00:00,jermeier@earthlink.net,[jdasovic@enron.com],None,None,calif regulatory eti,"Calif regulatory ETI Jeff: Some catch up items re ETI and California: I gather from Steve that you are changing the corp status of ETI to a LLC.? We may need to file for a formal transfer of ownership at the CPUC when you are ready. Also, we still need (some day soon) to file the ETI initial tariffs with the CPUC upon initiation of services in California (that is, when you want to start providing service in CA). We previously sent you several ICAs for California, though you probably will need some additional formal analysis.? Please let me know if the recent ICA Memo raised any questions or issues amongst your team. Trust you saw the interesting Enron energy article in Sunday's front section of the LA Times, and that your New Year is off to a bang. Jeremy Meier Blumenfeld Cohen",Jeremy Meier <jermeier@earthlink.net>,...,14,0,True,False,2,1,143,6,False,False
199156,ae93c0a772cc1d03acf03111cad689031bd3ff04c7e77b734cd13680af9ec578,<3463740.1075844828622.JavaMail.evans@thyme>,2001-02-22 16:22:00+00:00,exchangeinfo@nymex.com,[sara.shackleton@enron.com],None,None,(ms-12) switch of lessor,"(MS-12) SWITCH OF LESSOR NYMEX Membership Services February 22, 2001 Notice MS-012 SWITCH OF LESSOR Please be advised that effective with the close of business, February 22,= =20 2001, the following member(s) will switch their lessor within the Exchange: Karl Kovarik (KK-7270) NOTICE OF INTENTION TO LEASE ORIGINAL MEMBERSHIP Please be advised that effective with the close of business, February 22,= =20 2001, the following member(s) have given notice of intention to lease their= =20 sole membership privileges: Alan Kleinstein (NALA-4276) Mercerdees L. Murrell Members and Member Firms have (10) days from the date of this notice to=20 advise the Corporate Secretary=01,s Office of any claims in accordance with= Rule=20 2.51. Inquiries regarding the above should be addressed to the Member Services= =20 Department (212) 299-2379. __________________________________________________ Please click on the link below to indicate you have received this email. ""<URL> .com& refdoc=3D(MS-12)"" Note: If you click on the above line and nothing happens, please copy the text between the quotes, open your internet browser, paste it into the web site address and press Return.",exchangeinfo@nymex.com,...,16,3,True,False,2,1,175,7,False,False
199157,6c25803c0c03db516340b3401b835cf49dd50e32c744b0171788ee2519503a26,<15141472.1075847401327.JavaMail.evans@thyme>,2001-02-22 16:22:00+00:00,exchangeinfo@nymex.com,[tana.jones@enron.com],None,None,(ms-12) switch of lessor,"(MS-12) SWITCH OF LESSOR NYMEX Membership Services February 22, 2001 Notice MS-012 SWITCH OF LESSOR Please be advised that effective with the close of business, February 22,= =20 2001, the following member(s) will switch their lessor within the Exchange: Karl Kovarik (KK-7270) NOTICE OF INTENTION TO LEASE ORIGINAL MEMBERSHIP Please be advised that effective with the close of business, February 22,= =20 2001, the following member(s) have given notice of intention to lease their= =20 sole membership privileges: Alan Kleinstein (NALA-4276) Mercerdees L. Murrell Members and Member Firms have (10) days from the date of this notice to=20 advise the Corporate Secretary=01,s Office of any claims in accordance with= Rule=20 2.51. Inquiries regarding the above should be addressed to the Member Services= =20 Department (212) 299-2379. __________________________________________________ Please click on the link below to indicate you have received this email. ""<URL> refdo c=3D(MS-12)"" Note: If you click on the above line and nothing happens, please copy the text between the quotes, open your internet browser, paste it into the web site address and press Return.",exchangeinfo@nymex.com,...,16,3,True,False,2,1,175,6,False,False
199158,7475f55fc988552d92901df8e2e48aa50ce8986bff6d84bc03f9f6fad484c68b,<26244763.1075841225781.JavaMail.evans@thyme>,2001-05-23 20:12:00+00:00,greg.frers@enron.com,[jonathan.mckay@enron.com],None,None,re pricing,"re pricing Jon, This guy is being a pain. I wasn't able to close it yesterday so I'm at it again this morning. Could you re price a one year starting August 1,2001 thanks Greg",Greg Frers <Greg Frers/CAL/ECT@ECT>,...,20,2,True,False,2,1,35,2,True,False

In [3]:
!pip install email-reply-parser
!pip install mail-parser-reply
!pip install email-signature-detector

Collecting email-reply-parser
  Downloading email_reply_parser-0.5.12-py3-none-any.whl.metadata (828 bytes)
Downloading email_reply_parser-0.5.12-py3-none-any.whl (4.1 kB)
Installing collected packages: email-reply-parser
Successfully installed email-reply-parser-0.5.12

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: mail-parser-reply in c:\users\huy\appdata\local\programs\python\python313\lib\site-packages (1.36)

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting email-signature-detector
  Downloading email_signature_detector-0.1.10-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: numpy in c:\users\huy\appdata\local\programs\python\python313\lib\site-packages (from email-signature-detector) (2.3.1)
Collecting onnxruntime (from email-signature-detector)
  Downloading onnxruntime-1.27.0-cp313-cp313-win_amd64.whl.metadata (5.6 kB)
Collecting transformers (from email-signature-detector)
  Downloading transformers-5.12.1-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: torch in c:\users\huy\appdata\local\programs\python\python313\lib\site-packages (from email-signature-detector) (2.12.0)
Collecting flatbuffers (from onnxruntime->email-signature-detector)
  Downloading flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Requirement already satisfied: packaging in c:\users\huy\appdata\local\programs\python\python313\lib\site-packages (from onnxruntime->email-signature-detector) (26.0)
Requirement already satisfied: protobuf>=4.25.8 in c:\users\huy\appdata\local\programs\python\python313\lib\site-packages (from onnxruntime->email-signature-detector) (6.32.0)
Requirement already satisfied: filelock in c:\users\huy\appdata\local\programs\python\python313\lib\site-packages (from torch->email-signature-detector) (3.24.3)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\huy\appdata\local\programs\python\python313\lib\site-packages (from torch->email-signature-detector) (4.15.0)
Requirement already satisfied: setuptools<82 in c:\users\huy\appdata\local\programs\python\python313\lib\site-packages (from torch->email-signature-detector) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\huy\appdata\local\programs\python\python313\lib\site-packages (from torch->email-signature-detector) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\huy\appdata\local\programs\python\python313\lib\site-packages (from torch->email-signature-detector) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\huy\appdata\local\programs\python\python313\lib\site-packages (from torch->email-signature-detector) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\huy\appdata\local\programs\python\python313\lib\site-packages (from torch->email-signature-detector) (2026.4.0)
Collecting huggingface-hub<2.0,>=1.5.0 (from transformers->email-signature-detector)
  Downloading huggingface_hub-1.21.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: pyyaml>=5.1 in c:\users\huy\appdata\local\programs\python\python313\lib\site-packages (from transformers->email-signature-detector) (6.0.3)
Collecting regex>=2025.10.22 (from transformers->email-signature-detector)
  Using cached regex-2026.5.9-cp313-cp313-win_amd64.whl.metadata (41 kB)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers->email-signature-detector)
  Downloading tokenizers-0.22.2-cp39-abi3-win_amd64.whl.metadata (7.4 kB)
Requirement already satisfied: typer in c:\users\huy\appdata\local\programs\python\python313\lib\site-packages (from transformers->email-signature-detector) (0.25.1)
Collecting safetensors>=0.4.3 (from transformers->email-signature-detector)
  Downloading safetensors-0.8.0-cp310-abi3-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: tqdm>=4.60 in c:\users\huy\appdata\local\programs\python\python313\lib\site-packages (from transformers->email-signature-detector) (4.67.3)
Collecting click>=8.4.0 (from huggingface-hub<2.0,>=1.5.0->transformers->email-signature-detector)
  Downloading click-8.4.2-py3-none-any.whl.metadata (2.6 kB)
Collecting hf-xet<2.0.0,>=1.5.1 (from huggingface-hub<2.0,>=1.5.0->transformers->email-signature-detector)
  Downloading hf_xet-1.5.1-cp37-abi3-win_amd64.whl.metadata (4.9 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\huy\appdata\local\programs\python\python313\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers->email-signature-detector) (0.28.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\huy\appdata\local\programs\python\python313\lib\site-packages (from sympy>=1.13.3->torch->email-signature-detector) (1.3.0)
Requirement already satisfied: colorama in c:\users\huy\appdata\roaming\python\python313\site-packages (from tqdm>=4.60->transformers->email-signature-detector) (0.4.6)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\huy\appdata\local\programs\python\python313\lib\site-packages (from typer->transformers->email-signature-detector) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\users\huy\appdata\local\programs\python\python313\lib\site-packages (from typer->transformers->email-signature-detector) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\huy\appdata\local\programs\python\python313\lib\site-packages (from typer->transformers->email-signature-detector) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\huy\appdata\local\programs\python\python313\lib\site-packages (from jinja2->torch->email-signature-detector) (3.0.3)
Requirement already satisfied: anyio in c:\users\huy\appdata\local\programs\python\python313\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers->email-signature-detector) (4.12.1)
Requirement already satisfied: certifi in c:\users\huy\appdata\local\programs\python\python313\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers->email-signature-detector) (2026.1.4)
Requirement already satisfied: httpcore==1.* in c:\users\huy\appdata\local\programs\python\python313\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers->email-signature-detector) (1.0.9)
Requirement already satisfied: idna in c:\users\huy\appdata\local\programs\python\python313\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers->email-signature-detector) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\huy\appdata\local\programs\python\python313\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers->email-signature-detector) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\huy\appdata\local\programs\python\python313\lib\site-packages (from rich>=13.8.0->typer->transformers->email-signature-detector) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\huy\appdata\roaming\python\python313\site-packages (from rich>=13.8.0->typer->transformers->email-signature-detector) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\huy\appdata\local\programs\python\python313\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers->email-signature-detector) (0.1.2)
Downloading email_signature_detector-0.1.10-py3-none-any.whl (671 kB)
   ---------------------------------------- 0.0/671.5 kB ? eta -:--:--
   ---------------------------------------- 671.5/671.5 kB 3.1 MB/s eta 0:00:00
Downloading onnxruntime-1.27.0-cp313-cp313-win_amd64.whl (13.4 MB)
   ---------------------------------------- 0.0/13.4 MB ? eta -:--:--
   -- ------------------------------------- 0.8/13.4 MB 3.8 MB/s eta 0:00:04
   ---- ----------------------------------- 1.6/13.4 MB 4.3 MB/s eta 0:00:03
   -------- ------------------------------- 2.9/13.4 MB 4.9 MB/s eta 0:00:03
   ------------ --------------------------- 4.2/13.4 MB 5.3 MB/s eta 0:00:02
   ---------------- ----------------------- 5.5/13.4 MB 5.5 MB/s eta 0:00:02
   --------------------- ------------------ 7.1/13.4 MB 5.7 MB/s eta 0:00:02
   ------------------------ --------------- 8.1/13.4 MB 5.8 MB/s eta 0:00:01
   ----------------------------- ---------- 10.0/13.4 MB 6.1 MB/s eta 0:00:01
   ------------------------------------ --- 12.1/13.4 MB 6.5 MB/s eta 0:00:01
   ---------------------------------------- 13.4/13.4 MB 6.6 MB/s eta 0:00:00
Downloading transformers-5.12.1-py3-none-any.whl (11.2 MB)
   ---------------------------------------- 0.0/11.2 MB ? eta -:--:--
   ------ --------------------------------- 1.8/11.2 MB 9.3 MB/s eta 0:00:02
   -------------- ------------------------- 3.9/11.2 MB 9.6 MB/s eta 0:00:01
   -------------------- ------------------- 5.8/11.2 MB 9.8 MB/s eta 0:00:01
   ----------------------------- ---------- 8.1/11.2 MB 9.9 MB/s eta 0:00:01
   ------------------------------------- -- 10.5/11.2 MB 10.4 MB/s eta 0:00:01
   ---------------------------------------- 11.2/11.2 MB 10.1 MB/s eta 0:00:00
Downloading huggingface_hub-1.21.0-py3-none-any.whl (721 kB)
   ---------------------------------------- 0.0/721.1 kB ? eta -:--:--
   ---------------------------------------- 721.1/721.1 kB 9.8 MB/s eta 0:00:00
Using cached regex-2026.5.9-cp313-cp313-win_amd64.whl (277 kB)
Downloading safetensors-0.8.0-cp310-abi3-win_amd64.whl (355 kB)
Downloading tokenizers-0.22.2-cp39-abi3-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------- ----- 2.4/2.7 MB 11.3 MB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 10.7 MB/s eta 0:00:00
Downloading flatbuffers-25.12.19-py2.py3-none-any.whl (26 kB)
Downloading click-8.4.2-py3-none-any.whl (119 kB)
Downloading hf_xet-1.5.1-cp37-abi3-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   -------------------------- ------------- 2.6/4.0 MB 13.3 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 12.4 MB/s eta 0:00:00
Installing collected packages: flatbuffers, safetensors, regex, onnxruntime, hf-xet, click, huggingface-hub, tokenizers, transformers, email-signature-detector
  Attempting uninstall: click
    Found existing installation: click 8.3.1
    Uninstalling click-8.3.1:
      Successfully uninstalled click-8.3.1
Successfully installed click-8.4.2 email-signature-detector-0.1.10 flatbuffers-25.12.19 hf-xet-1.5.1 huggingface-hub-1.21.0 onnxruntime-1.27.0 regex-2026.5.9 safetensors-0.8.0 tokenizers-0.22.2 transformers-5.12.1

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
from email_reply_parser import EmailReplyParser
from mailparser_reply import EmailReplyParser
from email_signature_detector import ONNXSignaturePredictor

Failed to download model: HTTP Error 404: Not Found

RuntimeError: Could not download model from https://media.githubusercontent.com/media/numeo-ai/email-signature-detector/main/src/email_signature_detector/model/modernbert_sig_int8.onnx. Please download it manually to c:\Users\Huy\AppData\Local\Programs\Python\Python313\Lib\site-packages\email_signature_detector\model\modernbert_sig_int8.onnx

In [9]:
df1 = df[['sender', 'subject', 'body']]

df1

,sender,subject,body
0,mark.greenberg@enron.com,deloitte agreement,"Deloitte Agreement Michael I have attached below a revised version of the Channel Marketing Agreement with Deloitte. This document is the most current form of agreement that needs to be used for these deals and also reflects my comments. These comments are based upon the comments submitted by Deloitte. I have incorporated those that we discussed and made some additional comments. You will note that in the ""Fee Payment"" section, I have included the present value concept that you requested. I have not, however, defined this concept, but would assert that it should be defined in the agreement. Accordingly, please let me know how you want to define it. As I indicated above, this is a bit of a different form than the one you submitted to Deloitte for review. So that we can ensure that accurate documents are distributed, please allow us to prepare the drafts for distribution to potential channel marketing partners. Like the preparation of NDA's, this will enable the Legal Dept. to keep track of the agreement and ensure the right version is used. Please let me know if you should need anything further. Mark"
1,mary.cook@enron.com,raptor and the south american swap,"Raptor and the South American Swap Maricela has requested a copy of the termination notice for the referenced swap. I advised her that you would have done the document in relation to the swap (of which I think there was only one). I cannot remember if it was ever terminated. Can you coordinate this matter with Maricela. I am covering the rest of the Raptor requests. Cordially, Mary Cook Enron North America Corp. 1400 Smith, 38th Floor, Legal Houston, Texas 77002-7361 (713) 345-7732 (phone) (713) 646-3490 (fax) mary.cook@enron.com"
2,sara.shackleton@enron.com,raptor and the south american swap,"Mary: Remember, this is the swap that you finally decided to go ahead and terminate yourself. There was much confusion about how many S.A. swaps actually exsited (only one) and after sorting through the mess, when I asked if you had estabished a Raptor ""format for termination"", you decided to do the drafting. Let me know if there is a problem. Sara Shackleton Enron North America Corp. 1400 Smith Street, EB 3801a Houston, Texas 77002 713-853-5620 (phone) 713-646-3490 (fax) sara.shackleton@enron.com Forwarded by Sara Shackleton/HOU/ECT on 05/14/2001 01:31 PM Mary Cook 05/11/2001 11:38 AM"
3,cathy.sprowls@enron.com,enron canada 08/00 ontario variances,"Enron Canada 08/00 Ontario variances Phillip and Kam I put together spreadsheets summarizing the variances for Enron Canada purchases and sales for the Ontario region for August and it looks like we have a similar situation to July in that there are two liquidations on the purchase side that don't reference any particular Sitara deal that are directly offset in the liquidations for Transcanada Pipeline sales. If we net these two liquidations, it significantly reduces both variances. The Taggs are N63076.8 and 2 and N63076.C and 6. Thanks, Cathy"
4,errol.mclaughlin@enron.com,tenaska iii energy partners,"Tenaska III Energy Partners Please run a Mark to Market as of 12/31/2001 for TENASKA III Texas Partners. Please fax Sheila Trueblood at 402-691-9552 when you have printed the report. Thanks, Errol"
...,...,...,...
199154,m..taylor@enron.com,briefing @ enron office - re: economic stimulus pkg,"Briefing Enron Office RE: Economic Stimulus Pkg Participants: Linda Robertson, Chris Long Ed Coats"
199155,jermeier@earthlink.net,calif regulatory eti,"Calif regulatory ETI Jeff: Some catch up items re ETI and California: I gather from Steve that you are changing the corp status of ETI to a LLC.? We may need to file for a formal transfer of ownership at the CPUC when you are ready. Also, we still need (some day soon) to file the ETI initial tariffs with the CPUC upon initiation of services in California (that is, when you want to start providing service in CA). We previously sent you several ICAs for California, though you probably will need some additional formal analysis.? Please let me know if the recent ICA Memo raised any questions or issues amongst your team. Trust you saw the interesting Enron energy article in Sunday's front section of the LA Times, and that your New Year is off to a bang. Jeremy Meier Blumenfeld Cohen"
199156,exchangeinfo@nymex.com,(ms-12) switch of lessor,"(MS-12) SWITCH OF LESSOR NYMEX Membership Services February 22, 2001 Notice MS-012 SWITCH OF LESSOR Please be advised that effective with the close of business, February 22,= =20 2001, the following member(s) will switch their lessor within the Exchange: Karl Kovarik (KK-7270) NOTICE OF INTENTION TO LEASE ORIGINAL MEMBERSHIP Please be advised that effective with the close of business, February 22,= =20 2001, the following member(s) have given notice of intention to lease their= =20 sole membership privileges: Alan Kleinstein (NALA-4276) Mercerdees L. Murrell Members and Member Firms have (10) days from the date of this notice to=20 advise the Corporate Secretary=01,s Office of any claims in accordance with= Rule=20 2.51. Inquiries regarding the above should be addressed to the Member Services= =20 Department (212) 299-2379. __________________________________________________ Please click on the link below to indicate you have received this email. ""<URL> .com& refdoc=3D(MS-12)"" Note: If you click on the above line and nothing happens, please copy the text between the quotes, open your internet browser, paste it into the web site address and press Return."
199157,exchangeinfo@nymex.com,(ms-12) switch of lessor,"(MS-12) SWITCH OF LESSOR NYMEX Membership Services February 22, 2001 Notice MS-012 SWITCH OF LESSOR Please be advised that effective with the close of business, February 22,= =20 2001, the following member(s) will switch their lessor within the Exchange: Karl Kovarik (KK-7270) NOTICE OF INTENTION TO LEASE ORIGINAL MEMBERSHIP Please be advised that effective with the close of business, February 22,= =20 2001, the following member(s) have given notice of intention to lease their= =20 sole membership privileges: Alan Kleinstein (NALA-4276) Mercerdees L. Murrell Members and Member Firms have (10) days from the date of this notice to=20 advise the Corporate Secretary=01,s Office of any claims in accordance with= Rule=20 2.51. Inquiries regarding the above should be addressed to the Member Services= =20 Department (212) 299-2379. __________________________________________________ Please click on the link below to indicate you have received this email. ""<URL> refdo c=3D(MS-12)"" Note: If you click on the above line and nothing happens, please copy the text between the quotes, open your internet browser, paste it into the web site address and press Return."
199158,greg.frers@enron.com,re pricing,"re pricing Jon, This guy is being a pain. I wasn't able to close it yesterday so I'm at it again this morning. Could you re price a one year starting August 1,2001 thanks Greg"

In [ ]:
train = pd.read_parquet('../data/train.parquet', engine='pyarrow')

train[:10000]['body'].str.regexp(r'escalation', regex=True)

,id,message_id,date,sender,to,cc,bcc,subject,body,x_from,...,x_origin,x_filename,source_file,thread_id,parent_id,sequence,is_forward,is_reply,sender_domain,recipient_domain
0,889ca4a4bfbe6f8269b26b649d900562a2abd15c2508c6bf7e9b7d4012034cb7,<24861977.1075858950944.JavaMail.evans@thyme>,2001-09-25 18:08:56+00:00,mark.greenberg@enron.com,[michael.bridges@enron.com],"[c..koehler@enron.com, tana.jones@enron.com]","[c..koehler@enron.com, tana.jones@enron.com]",deloitte agreement,"Deloitte Agreement Michael I have attached below a revised version of the Channel Marketing Agreement with Deloitte. This document is the most current form of agreement that needs to be used for these deals and also reflects my comments. These comments are based upon the comments submitted by Deloitte. I have incorporated those that we discussed and made some additional comments. You will note that in the ""Fee Payment"" section, I have included the present value concept that you requested. I have not, however, defined this concept, but would assert that it should be defined in the agreement. Accordingly, please let me know how you want to define it. As I indicated above, this is a bit of a different form than the one you submitted to Deloitte for review. So that we can ensure that accurate documents are distributed, please allow us to prepare the drafts for distribution to potential channel marketing partners. Like the preparation of NDA's, this will enable the Legal Dept. to keep track of the agreement and ensure the right version is used. Please let me know if you should need anything further. Mark","Greenberg, Mark </O=ENRON/OU=NA/CN=RECIPIENTS/CN=MGREENBE>",...,Jones-T,TJONES (Non-Privileged).pst,Enron Data,00010e28ea14990d1df8a1c9399506b429f0f8f2de3a109603e91556fef2fb37,None,1,False,False,enron.com,[enron.com]
1,4ad8b7360da6721377f00f7ed69e66a02a1f06460d97664634f7c01ff6bdec61,<33442183.1075844794684.JavaMail.evans@thyme>,2001-05-11 11:38:00+00:00,mary.cook@enron.com,[sara.shackleton@enron.com],"[gordon.mckillop@enron.com, joel.ephross@enron.com, maricela.trevino@enron.com]","[gordon.mckillop@enron.com, joel.ephross@enron.com, maricela.trevino@enron.com]",raptor and the south american swap,"Raptor and the South American Swap Maricela has requested a copy of the termination notice for the referenced swap. I advised her that you would have done the document in relation to the swap (of which I think there was only one). I cannot remember if it was ever terminated. Can you coordinate this matter with Maricela. I am covering the rest of the Raptor requests. Cordially, Mary Cook Enron North America Corp. 1400 Smith, 38th Floor, Legal Houston, Texas 77002-7361 (713) 345-7732 (phone) (713) 646-3490 (fax) mary.cook@enron.com",Mary Cook,...,SHACKLETON-S,sshackle.nsf,Enron Data,0001d99832e0e1eec3b35ed83b00932ec3da2a075ab36ebdd0ae8f2ea740bed3,None,1,False,False,enron.com,[enron.com]
2,53eb6faafab020188fdfe4bb8870b281604f3b8aaa7e6ad07d2a0023a5dca02f,<7294597.1075844926117.JavaMail.evans@thyme>,2001-05-14 13:33:00+00:00,sara.shackleton@enron.com,[mary.cook@enron.com],None,None,raptor and the south american swap,"Mary: Remember, this is the swap that you finally decided to go ahead and terminate yourself. There was much confusion about how many S.A. swaps actually exsited (only one) and after sorting through the mess, when I asked if you had estabished a Raptor ""format for termination"", you decided to do the drafting. Let me know if there is a problem. Sara Shackleton Enron North America Corp. 1400 Smith Street, EB 3801a Houston, Texas 77002 713-853-5620 (phone) 713-646-3490 (fax) sara.shackleton@enron.com Forwarded by Sara Shackleton/HOU/ECT on 05/14/2001 01:31 PM Mary Cook 05/11/2001 11:38 AM",Sara Shackleton,...,SHACKLETON-S,sshackle.nsf,Enron Data,0001d99832e0e1eec3b35ed83b00932ec3da2a075ab36ebdd0ae8f2ea740bed3,<33442183.1075844794684.JavaMail.evans@thyme>,2,False,False,enron.com,[enron.com]
3,115a2c7a146730ed9610a46f081e6286abaa9d1fc9acd9107991b34c4f7b5862,<29107275.1075858234356.JavaMail.evans@thyme>,2000-12-04 15:16:00+00:00,cathy.sprowls@enron.com,"[kam.keiser@enron.com, phillip.love@enron.com]",None,None,enron canada 08/00 ontario variances,"Enron Canada 08/00 Ontario variances Phillip and Kam I put together spreadsheets summarizing the variances for Enron Canada purchases and sales for the Ontario region for August and it looks like we have a similar situation to July in that there are two liquidations on the purchase side that don't reference any particular Sitara deal that are directly offset in the liquidations for Transcanada Pipeline sales. If we net these two liquidations, it significantly reduces both variances. The Taggs are N63076.8 and 2 and N63076.C and 6. Thanks, Cathy",Cathy Sprowls,...,Love-P,plove.nsf,Enron Data,00023f219ad5a4f69d7a935d5d27b0ca9fc22b80a707f15ca1b0fe493639774f,None,1,False,False,enron.com,[enron.com]
4,e16d4c4088f9c377dcd04b271edd4032ab3d57de4b4c52ab486c6a09026dfa01,<1161169.1075857401320.JavaMail.evans@thyme>,2001-03-01 10:42:00+00:00,errol.mclaughlin@enron.com,[sherry.dawson@enron.com],None,None,tenaska iii energy partners,"Tenaska III Energy Partners Please run a Mark to Market as of 12/31/2001 for TENASKA III Texas Partners. Please fax Sheila Trueblood at 402-691-9552 when you have printed the report. Thanks, Errol",Errol McLaughlin,...,McLaughlin-E,emclaug.nsf,Enron Data,000261a20cf197d0511229c43ef5e2cfd897af6c8e47ccc20ad75bdaa77ee6b0,None,1,False,False,enron.com,[enron.com]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,bdd7e902dd9c65d7cddc620ea70d1be7d48dd2fd12f6f0161ea146faa1d4c36c,<25988792.1075847409656.JavaMail.evans@thyme>,2001-03-09 07:33:00+00:00,matilda.machado@enron.com,[tana.jones@enron.com],None,None,"eol help desk question, cp id 5177 saskenergy incorporated,\n global contract 96013849","Re: EOL Help Desk Question, CP ID 5177 SaskEnergy Incorporated, Global Contract 96013849 Hi Tana, Further to Karen Lambert's email below, could you please let me know what the status is with SaskEnergy? Are they understanding the fact that their EOL transactions will fall under the Master Agreement's terms and conditions? Let me know if I need to contact them. Thanks, Matilda Forwarded by Matilda Machado/CAL/ECT on 03/09/2001 08:31 AM From: Karen Lambert on 03/08/2001 03:32 PM CST",Matilda Machado,...,JONES-T,tjones.nsf,Enron Data,0b7011bd36b51f94e42411b591b0bc938672b762136fb3bccfdecf6e758eae6a,None,1,False,True,enron.com,[enron.com]
9996,d0dd4b362af3c209162073e718bb179dbb01a624c402ceff310024af91d8c5d0,<1083860.1075847551569.JavaMail.evans@thyme>,2001-03-09 08:59:00+00:00,tana.jones@enron.com,[matilda.machado@enron.com],None,None,"eol help desk question, cp id 5177 saskenergy incorporated,\n global contract 96013849","Re: EOL Help Desk Question, CP ID 5177 SaskEnergy Incorporated, Global Contract 96013849 I spoke to the woman at Sask and she's ok on everything. Matilda Machado 03/09/2001 08:33 AM",Tana Jones,...,JONES-T,tjones.nsf,Enron Data,0b7011bd36b51f94e42411b591b0bc938672b762136fb3bccfdecf6e758eae6a,<25988792.1075847409656.JavaMail.evans@thyme>,2,False,True,enron.com,[enron.com]
9997,28c20e38f8b3cccb89b9992a45c60964fb012c0d6d4c072f6973bbb47a321e7c,<16952250.1075853760680.JavaMail.evans@thyme>,2000-06-02 10:48:00+00:00,timothy.ray@enron.com,[colleen.sullivan@enron.com],"[chris.germany@enron.com, john.henderson@enron.com]","[chris.germany@enron.com, john.henderson@enron.com]",ces supply management agreement,"CES Supply Management Agreement New Power Company is current working on the acquisition of CES' mass market customers. In light of the acquisition, there are issues that surround our relationship with ENA as we step into the supply management agreement. Below are the observations that I have. I would like to get you feedback on these. If necessary, let's get together to discuss the ramifications. 1) We are purchasing customers within only twelve markets. As such, we will only interpret the language of the agreement related to ""existing markets"" as applying to only those twelve markets. For other markets that we conduct business in, we would choose to make a decision on supplier and load management even if it is an LDC identified as an existing market under the agreement. In essence, we see the supply management agreement being bi-furcated since CES is selling C&I to another marketer. 2) My interpretation is that New Power Company will only be on the hook for capacity and storage charges as they apply to mass markets. This would include capacity and/or storage allocations received on CVA, CMD, AGL. In addition, it would include the FSS and SST purchased on COH. It would also include the following transportation agreements: 61822, 61825, 61838, 61990, 64939, 65418, 62164. There are some capacity agreements on TCO for CPA(65041, 65042) and BGE(65108) that were purchased by CES for both C&I and mass markets. It is our contention that we will only be on the hook for the demand charges related to the capacity covering mass market purchase commitments identified in the schedules of the purchase agreement All un-utilized capacity would to stay with CES and/or buyer of the C&I agreements. 3) We need to discuss the application of the contract to additional capacity that New Power procures applicable to the periods prior to Apr. 1, 2001. I want to keep this capacity separate and under our control. I will need your viewpoint on this. If ENA feels strongly that we must place the capacity under the supply management agreement, then I would want to discuss our ability to market any excess capacity in open market. Bottom-line, I want to avoid gas costs being inflated due to my inability to receive value for un-utilized capacity. 4) I would like to get your viewpoint on the right of first refusal clause. My view would be that its applicable would be made to transactions of similar nature and service level. (supply management) To the degree that New Power chose after the primary term to manage its supply, all supply only transactions would not be subject to this clause. I know you will need to review the contract. We have some time to discuss these issues, but would like to have feedback from you no later than next Friday, if at all possible. I can be reached at ext 39475. Thanks for your help.",Timothy L Ray,...,Germany-C,cgerman.nsf,Enron Data,0b7026bf4ed9340392b4914659e3c0a231488f516e6be4cd63a8b0888cb0922a,None,1,False,False,enron.com,[enron.com]
9998,801c6323ebcc76de39b6ce8ce0422d4a730a72f4b1feca5332a1da0b572b8001,<5795850.1075853760703.JavaMail.evans@thyme>,2000-06-02 11:07:00+00:00,chris.germany@enron.com,"[molly.johnson@enron.com, scott.goodell@enron.com]",None,None,ces supply management agreement,Hi team. Do not discuss this with anyone at CES or EES please. May not be a problem but just in case. Forwarded by Chris Germany/HOU/ECT on 06/02/2000 11:06 AM Timothy L Ray@EES 06/02/2000 10:48 AM,Chris Germany,...,Germany-C,cgerman.nsf,Enron Data,0b7026bf4ed9340392b4914659e3c0a231488f516e6be4cd63a8b0888cb0922a,<16952250.1075853760680.JavaMail.evans@thyme>,2,False,False,enron.com,[enron.com]
9999,7c711c40898c1710c18af6f8ffc844014a4561778bca07b5e2c98a5d1fb4afbc,<2346716.1075853760727.JavaMail.evans@thyme>,2000-06-02 12:53:00+00:00,scott.goodell@enron.com,"[chris.germany@enron.com, colleen.sullivan@enron.com, dick.jenkins@enron.com]",None,None,ces supply management agreement,"Re: CES Supply Management Agreement Here is some detail on the contracts mentioned in the brief... For these 5 contracts, ENA/CES has Right of First Refusal for the next bid process. Jeff Porter at CES is aware of TCO's deadline for matching. Rate for these five contracts is $5.171/month. They expire 10/31/2000. 61822 4,000/d delivery to 23n-7 61825 4,000/d delivery to 23n-2 61838 1,000/d delivery to 23-4 61990 2,000/d delivery to 23-4 65418 500/d delivery to 23n-7 These five contracts have various terms and delivery points. No Right of First Refusal. 64939 2,300/d delivery to COH 8-35 term ends 9/30/2000 $6.3980 Max 62164 2,000/d delivery to COH 7-9 term ends 12/31/2000 $3.0417 Discounted 65041 9,619/d delivery to Various Op-25 term ends 10/31/2000 $6.4860 Max 65042 4,427/d delivery to 25e-25 term ends 10/31/2000 $6.4860 Max 65108 5,000/d delivery to 4 (BG&E) term ends 4/30/2001 $6.449 Max Let me know if you need any additional information. Scott Chris Germany@ECT 06/02/2000 11:07 AM",Scott Goodell,...,Germany-C,cgerman.nsf,Enron Data,0b7026bf4ed9340392b4914659e3c0a231488f516e6be4cd63a8b0888cb0922a,<5795850.1075853760703.JavaMail.evans@thyme>,3,False,True,enron.com,[enron.com]

In [179]:
df['thread_id']

0         00002a1f84f3503882a68eaefc196b85d4a3a7d119dd10e0166c14d9a0f18c60
1         00002a1f84f3503882a68eaefc196b85d4a3a7d119dd10e0166c14d9a0f18c60
2         00002a1f84f3503882a68eaefc196b85d4a3a7d119dd10e0166c14d9a0f18c60
3         00002a1f84f3503882a68eaefc196b85d4a3a7d119dd10e0166c14d9a0f18c60
4         00002a1f84f3503882a68eaefc196b85d4a3a7d119dd10e0166c14d9a0f18c60
                                        ...
248944    fffb4547b317e3cac963375418de676485def2b328d86b206acf9b73ea1d7975
248945    fffb4547b317e3cac963375418de676485def2b328d86b206acf9b73ea1d7975
248946    fffc6a5e03509e640b8c5cf254d240e0bcb468a6e314cf0c25d50b785ee79eae
248947    fffce0f38860387fe6f3217c90c6968f05a3fc0cf43a3c271c8eb42e01fb5808
248948    fffe37c5539b5051b358f7758d578f0b74f7fcd11c72a87accfcebd0c6f927c0
Name: thread_id, Length: 248949, dtype: object

In [159]:
data

,id,message_id,date,sender,to,cc,bcc,subject,body,x_from,x_to,x_cc,x_bcc,x_folder,x_origin,x_filename,source_file
0,b399fa1ba5ec06ccf8ead1049a53be981d0ebb39ee2c941998281a328c7920b4,<17334447.1075857585446.JavaMail.evans@thyme>,2000-11-16 17:30:00+00:00,msagel@home.com,[jarnold@enron.com],None,None,Status,"Status John: I'm not really sure what happened between us.? I was under the impression after my visit to Houston that we were about to enter into a trial agreement for my advisory work.? Somehow,?this never occurred.? Did I say or do something wrong to screw this up??? I don't know if you've blown this whole thing off, but I still hope you are interested in trying?to create an arrangement.? As a courtesy, here is my report from this past weekend.? If you are no longer interested in my work, please tell me so.??Best wishes, Mark Sagel Psytech Analytics (410)308-0245? energy2000-1112.doc","""Mark Sagel"" <msagel@home.com>","""John Arnold"" <jarnold@enron.com>",None,None,\John_Arnold_Dec2000\Notes Folders\Notes inbox,Arnold-J,Jarnold.nsf,Enron Data
1,84b07d7a0a17b545896f670f92d200e86843c2796147d9f65e8ce1ebe15f5157,<19171686.1075857585034.JavaMail.evans@thyme>,2000-12-08 13:05:00+00:00,slafontaine@globalp.com,[john.arnold@enron.com],None,None,re:summer inverses,re:summer inverses i suck-hope youve made more money in natgas last 3 weeks than i have. mkt shud be getting bearish feb forward-cuz we already have the weather upon us-fuel switching and the rest shud invert the whole curve not just dec cash to jan and feb forward???? have a good weekend john,slafontaine@globalp.com,John.Arnold@enron.com,None,None,\John_Arnold_Dec2000\Notes Folders\Notes inbox,Arnold-J,Jarnold.nsf,Enron Data
2,f7482dd06262f46d341e733aa0c2fb55cb1e257ea153d078c69972567fc7fa6a,<29887033.1075857630725.JavaMail.evans@thyme>,2001-05-15 16:43:00+00:00,iceoperations@intcx.com,"[icehelpdesk@intcx.com, internalmarketing@intcx.com]",None,None,The WTI Bullet swap contracts,"The WTI Bullet swap contracts Hi, Following the e-mail you have received yesterday concerning the new WTI bullet swap contracts, we would like to summarize what we have done on the ICE system yesterday evening: -Deleted WTI monthly time spreads -Deleted WTI/Brent monthly diff spreads (spread with legging) -Deleted 1% NYH Harbor Fuel Oil Crack monthly (spread with legging) -Added WTI/Brent monthly diff spreads (spread with NO legging) -Added 1% NYH Harbor Fuel Oil Crack monthly (spread with NO legging) Unfortunately the WTI/Brent and the 1% NYH Fuel Oil Crack contracts (with the legging functionality) have been removed from your portfolios. You will need to add the first four nearby months' contracts to your portfolios by going to Admin Manage Portfolios Edit your portfolio.... Please do not hesitate to contact us is you have any question: Helpdesk on +1 770 738 2101 (US) Stephanie Trabia: +44 207 484 5546 (UK) Regards, Stephanie Trabia Marketing Manager IntercontinentalExchange Tel +44 207 484 5546 Fax +44 207 484 5100 Mob +44 77 33 261 268 stephanie.trabia@intcx.com",ICE Operations <ICEOperations@intcx.com>,"**ICEHELPDESK <**ICEHELPDESK@intcx.com>, **Internal Marketing\t <**InternalMarketing@intcx.com>",None,None,\John_Arnold_Jun2001\Notes Folders\Notes inbox,Arnold-J,Jarnold.nsf,Enron Data
3,25441e5a837fefda50527731fdbcdf0848663be82cd1ce14e1f37fb25814c54f,<2526360.1075857584903.JavaMail.evans@thyme>,2000-12-12 07:52:00+00:00,klarnold@flash.net,[john.arnold@enron.com],None,None,Fwd: NYTimes.com Article: Suspended Rabbi Quits Seminary Presidency,Fwd: NYTimes.com Article: Suspended Rabbi Quits Seminary Presidency >Sender: articles-email@ms1.lga2.nytimes.com >Reply-To: judgergm@swbell.com >From: judgergm@swbell.com >To: klarnold@flash.net,Karen Arnold <klarnold@flash.net>,john.arnold@enron.com,None,None,\John_Arnold_Dec2000\Notes Folders\Notes inbox,Arnold-J,Jarnold.nsf,Enron Data
4,c2995c6a70b953ee66c21d8a509ebfbfaca28277917beb52fa0dc64fc49ef1d8,<30102065.1075857630952.JavaMail.evans@thyme>,2001-05-15 06:59:00+00:00,soblander@carrfut.com,[soblander@carrfut.com],None,None,daily charts and matrices as hot links 5/15,"daily charts and matrices as hot links 5/15 The information contained herein is based on sources that we believe to be reliable, but we do not represent that it is accurate or complete. Nothing contained herein should be considered as an offer to sell or a solicitation of an offer to buy any financial instruments discussed herein. Any opinions expressed herein are solely those of the author. As such, they may differ in material respects from those of, or expressed or published by on behalf of Carr Futures or its officers, directors, employees or affiliates. 2001 Carr Futures The charts are now available on the web by clicking on the hot link(s) contained in this email. If for any reason you are unable to receive the charts via the web, please contact me via email and I will email the charts to you as attachments. Distillate and unleaded charts to follow. Crude <URL> Natural Gas <URL> Nat Gas Strip Matrix <URL> Nat Gas Spread Matrix <URL> Crude and Products Spread Matrix <URL> Carr Futures 150 S. Wacker Dr., Suite 1500 Chicago, IL 60606 USA Tel: 312-368-6149 Fax: 312-368-2281 soblander@carrfut.com <URL>",SOblander@carrfut.com,soblander@carrfut.com,None,None,\John_Arnold_Jun2001\Notes Folders\Notes inbox,Arnold-J,Jarnold.nsf,Enron Data
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447412,0bdb0ac3a0dc0f264c12ec3525328c4aee0c92b9edc46c35f3f1f948087155f5,<20441369.1075863375765.JavaMail.evans@thyme>,2001-09-21 18:48:44+00:00,bobbie.campbell@enron.com,"[cassandra.schultz@enron.com, david.gorte@enron.com, david.port@enron.com, e.sullo@enron.com, l..carson@enron.com, michael.tribolet@enron.com, rebecca.carter@enron.com, rick.buy@enron.com, s..bradford@enron.com, ted.murphy@enron.com]",None,None,Review Board Books w/Rebecca\n C./BillB/DaveG/MichaelT/Cassandra/TedM/RickC/SharonS/RBuy,"Review Board Books w/Rebecca C./BillB/DaveG/MichaelT/Cassandra/TedM/RickC/SharonS/RBuy When: Monday, September 24, 2001 12:00 PM-1:30 PM (GMT-06:00) Central Time (US Canada). Where: EB2831","Campbell, Bobbie </O=ENRON/OU=NA/CN=RECIPIENTS/CN=BCAMPBE>","Carter, Rebecca </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Rcarte1>, Buy, Rick </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Rbuy>, Tribolet, Michael </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Mtribole>, Gorte, David </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Dgorte>, Bradford, William S. </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Wbradfo>, Sullo, Sharon E </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Ssullo>, Murphy, Ted </O=ENRON/OU=NA/CN=RECIPIENTS/CN=EU/cn=Recipients/cn=tmurph1>, Port, David </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Dport>, Schultz, Cassandra </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Cschult>, Carson, Rick L. </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Rcarson>",None,None,"\RBUY (Non-Privileged)\Buy, Rick\Inbox",Buy-R,RBUY (Non-Privileged).pst,Enron Data
447413,0ac645e6697f87ad559300a183e0797b4d8ce087477eabd7ada9a02214f9566f,<18115560.1075863371090.JavaMail.evans@thyme>,2001-09-04 15:40:08+00:00,sharron.westbrook@enron.com,"[a..lindholm@enron.com, bob.butts@enron.com, shawn.kilchrist@enron.com]","[dortha.gray@enron.com, k..heathman@enron.com, sandy.lewelling@enron.com]","[dortha.gray@enron.com, k..heathman@enron.com, sandy.lewelling@enron.com]",Audit Committee Materials meeting,Audit Committee Materials meeting Two meetings have been scheduled to prepare the materials for the October 8 Audit and Compliance Committee books. Preliminary Meeting September 13 2:00 PM EB5023 (Rick Causey's office) Final Prep Meeting and review of Materials September 24 9:00 AM EB5023 (RickCausey's office),"Westbrook, Sharron </O=ENRON/OU=NA/CN=RECIPIENTS/CN=SWESTBR>","'David.b.duncan@andersen.com', Buy, Rick </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Rbuy>, Butts, Bob </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Rbutts>, Lindholm, Tod A. </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Tlindho>, Kilchrist, Shawn </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Skilchri>","Gray, Dortha </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Dgray>, Heathman, Karen K. </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Kheathm>, Lewelling, Sandy </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Slewell>, 'shannon.d.adlong@andersen.com'",None,"\RBUY (Non-Privileged)\Buy, Rick\Inbox",Buy-R,RBUY (Non-Privileged).pst,Enron Data
447414,a793085ec108f61f5b8d78b075a4270492464bd3903d101ea95eeb9ad382b1c5,<9719707.1075862189729.JavaMail.evans@thyme>,2001-11-05 09:20:12+00:00,ted.murphy@enron.com,"[david.port@enron.com, rick.buy@enron.com, s..bradford@enron.com]",None,None,Credit Story,"Credit Story Rick/Bill/David, Generally, we have managed to keep our main counterparts transacting, but things are tight. We are signing netting agreements and agreeing to collateral threshholds, but we are negotiating hard where we think that we will be so close to collateral lines in the next few months that we would actually have to post. As we go into this week, we need to hold on to those we have, incrementally open up a few more, and start to get people to business as usual. Amongst the things that continues to be missing are the OFFICIAL STORY (we have access to the newspaper here, too), good communication regarding global relationships, and calendar and status of new developments regarding credit facilities, equity issuance/raising..... Not that some of it is getting through, it just comes through random channels and we know very little more than our counterparts that have a subscription to the Wall Street Journal. To that end, it has been suggested here that Houston (PR?) with RAC/Finance develop a daily script of talking points for the masses. We have traders and credit people talking all day to counterparts they really could use a strong story to tell without have to think about it. I am very confident that I can tell a reasonable story myself, but I am concerned that I do not have all the facts at my disposal and my guess is that the average trader/credit specialist is probably at a greater disadvantage. Thoughts? Ted","Murphy, Ted </O=ENRON/OU=NA/CN=RECIPIENTS/CN=EU/CN=RECIPIENTS/CN=TMURPH1>","Bradford, William S. </O=ENRON/OU=NA/CN=RECIPIENTS/CN=WBRADFO>, Buy, Rick </O=ENRON/OU=NA/CN=RECIPIENTS/CN=RBUY>, Port, David </O=ENRON/OU=NA/CN=RECIPIENTS/CN=DPORT>",None,None,"\RBUY (Non-Privileged)\Buy, Rick\Inbox",Buy-R,RBUY (Non-Privileged).pst,Enron Data
447415,b4c865058be34ce716c6deb6df71be866af825eb6cfcd457609c2fc6fac11a98,<13468574.1075863381452.JavaMail.evans@thyme>,2001-10-17 23:02:14+00:00,cassandra.schultz@enron.com,"[david.port@enron.com, rick.buy@enron.com]","[frank.hayden@enron.com, ted.murphy@enron.com]","[frank.hayden@enron.com, ted.murphy@enron.com]",Commodity Group Limit Issue,"Commodity Group Limit Issue In addition to the Concentration Limit NA Gas P/L notification issued below, I believe there should also be a P/L Notification on NA Gas Commodity Group Limit, but the DPR reporting does not reflect it currently. Lavorato has a ""Cross-Commodity"" line on the Business Unit DPR that reflected $18,670 MM VaR and ($23,583 MM) P/L. This does not roll up into the NA Gas Commodity Group line which had $55,509 VaR and ($67,838 MM) P/L, both below the $85 MM Commodity Group limit, but it was appropriately included in the Business Unit VaR and P/L. I obtained the detail of this cross-commodity line by reviewing the Concentration Limit DPR: VaR P/L Gas 18,580 (24,659) (a) Power 233 376 Residual Fuel 545 F/X 155 Total (23,583) Business Unit DPR: NA Gas 55,509 (67,838) Gas in Cross-Commodity (24,659) (a) Total (92,497) According to the Policy, all commodities traded within a business unit should have a limit approved by the CRO. I can see how we might want to allow some leeway in the application of that requirement, but not to the extent of $18.6 MM VaR. So my recommendation is: 1) Require the Gas and Power position in Lavorato's cross-commodity books to be rolled up into Gas and Power Commodity Group results on the Business Unit DPR, and compared to the Commodity Group VaR limits established for Gas and Power. This would not have caused a VaR violation today as we recently increased the commodity group limit for Gas to $85 MM, only a P/L notification. And while Power is not material now, it has been in the past, and could easily be again, and Power is a standard Americas commodity group. 2) Grant an ""Other"" VaR limit of $X (a small amount) that authorizes Lavorato to trade other commodities. That at least limits this other activity and will require him to discuss with the you if he wants to take an exceptionally large position in a commodity other than Gas and Power. I think protecting the integrity of the Commodity Group limits is also important from the perspective that the Business Unit management is not really responsible for the Concentration Limit DPR (Lavorato and Kitchen do not even have access to view it!), and they are not on the distribution list for notifications on those limits. So as far as Lavorato/Kitchen is concerned, as currently reported they had no P/L notifications today as Power made some income so the business unit only lost ($97MM) vs it's $100 MM VaR limit. But the company lost ($119 MM) on gas, as noted in the e-mail below, and proper reporting of all of Lavorato's gas and power positions in comparison to his corresponding Commodity Group limits would have resulted in a Commodity Group P/L notification of ($92 MM) vs. the $85 MM limit. We already eliminated all the position limits for Gas and Power. Although the Concentration Limit DPR is accurately reflecting activity, we should probably make sure the VaR and P/L is being clearly reported on the Business Unit DPR as well, as that is the one that much of management of the company is still focused on. Do you agree? We can discuss when you're back in the office. Regards, Cassandra.","Schultz, Cassandra </O=ENRON/OU=NA/CN=RECIPIENTS/CN=CSCHULT>","Buy, Rick </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Rbuy>, Port, David </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Dport>","Hayden, Frank </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Fhayden>, Murphy, Ted </O=ENRON/OU=NA/CN=RECIPIENTS/CN=EU/cn=Recipients/cn=tmurph1>",None,"\RBUY (Non-Privileged)\Buy, Rick\Inbox",Buy-R,RBUY (Non-Privileged).pst,Enron Data
447416,a3004d5702ced264450b419147373e15105b4eda4bfa514cf5159c8d7bfe201d,<7591962.1075862193703.JavaMail.evans@thyme>,2001-11-21 21:24:39+00:00,terri.greenlee@enron.com,[rick.buy@enron.com],None,None,Calley Hayes with Deutsch Bank,"Calley Hayes with Deutsch Bank Rick, Calley's numbers are as follows: Office: 212.469.8981 Cell: 917.854.3823 Home: 914.234.0158 Terri x33565","Greenlee, Terri </O=ENRON/OU=NA/CN=RECIPIENTS/CN=TGREENLE>","Buy, Rick </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Rbuy>",None,None,"\RBUY (Non-Privileged)\Buy, Rick\Inbox",Buy-R,RBUY (Non-Privileged).pst,Enron Data

In [154]:
data.iloc[447412]

id                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                0bdb0ac3a0dc0f264c12ec3525328c4aee0c92b9edc46c35f3f1f948087155f5
message_id                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <20441369.1075863375765.JavaMail.evans@thyme>
date                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     2001-09-21 18:48:44+00:00
sender                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   bobbie.campbell@enron.com
to                                                                                                                                                                                                                                                                                                                                                                                       [cassandra.schultz@enron.com, david.gorte@enron.com, david.port@enron.com, e.sullo@enron.com, l..carson@enron.com, michael.tribolet@enron.com, rebecca.carter@enron.com, rick.buy@enron.com, s..bradford@enron.com, ted.murphy@enron.com]
cc                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            None
bcc                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           None
subject                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Review Board Books w/Rebecca\n C./BillB/DaveG/MichaelT/Cassandra/TedM/RickC/SharonS/RBuy
body                                                                                                                                                                                                                                                                                                                                                                                                                                 Review Board Books w/Rebecca C./BillB/DaveG/MichaelT/Cassandra/TedM/RickC/SharonS/RBuy When: Monday, September 24, 2001 12:00 PM-1:30 PM (GMT-06:00) Central Time (US Canada). Where: EB2831
x_from                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Campbell, Bobbie </O=ENRON/OU=NA/CN=RECIPIENTS/CN=BCAMPBE>
x_to           Carter, Rebecca </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Rcarte1>, Buy, Rick </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Rbuy>, Tribolet, Michael </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Mtribole>, Gorte, David </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Dgorte>, Bradford, William S. </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Wbradfo>, Sullo, Sharon E </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Ssullo>, Murphy, Ted </O=ENRON/OU=NA/CN=RECIPIENTS/CN=EU/cn=Recipients/cn=tmurph1>, Port, David </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Dport>, Schultz, Cassandra </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Cschult>, Carson, Rick L. </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Rcarson>
x_cc                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          None
x_bcc                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         None
x_folder                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    \RBUY (Non-Privileged)\Buy, Rick\Inbox
x_origin                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Buy-R
x_filename                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               RBUY (Non-Privileged).pst
source_file                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Enron Data
Name: 447412, dtype: object

In [80]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,248939,248940,248941,248942,248943,248944,248945,248946,248947,248948
id,47366c5f2389afff7d85e0c121750353e65fcf47cc3421726e7f6cc446d82e70,ab9e47992a99c4e6353cc79ec12a965a40bf2029bb354081d38d9a7b80cd49b3,3a88adf0af5ec9037aed637b9aa882e752897927c5c2aeabaaadd4d84363c3c4,ca7a881a2778c7208625d93a6d9f51c08c57b85537d93351664c0d4eb62da58c,202579047e5a14c006cefc75c29b3a348662c5b5305377ab783318a1e80f6b57,ac1a22a9704ee4482166e1eb957aef6f8fd99d9be770b282ab513cda2a7504a3,ca231f95406843b9865f5c8b6ef787fbe838d59f076bffd5d243d7da67b9562e,5a40839991f59b46d16c7fee0f996da2f33e74125ebe8e4904c17036516d876e,889ca4a4bfbe6f8269b26b649d900562a2abd15c2508c6bf7e9b7d4012034cb7,f8deeab24d656858dcbea56216712ea9989a78657ebeac0d575a56f01134dff0,...,a30d9b7dabfef03b424bff4ce126e9fd5052b255f90ebe095eab645361e8f639,0a7dd7df4c2ce3da80fdccae393b1ecc95e7d91a5f52fdc590f21b7930aefe58,36cc33ca85e16acd0ad745bb8343683efa00302f0380aa11dc885960284ee741,c9d1cd8c0ddfc27ee52a48da5a3c8b22fcab586c8c6d4e226d6a5ccefa9f6630,0b0b0167eaf7d7e1267d0e70a1c44fa215e4689829b49f357db07b0413e7863a,01f6393ac0334b2a9048b170fa645cd9f62ec61590a366b49069fbe6bdac3957,6bb593fc0bc97b7c4a3d0dada906498fa43c4b6210eb44e7fb36130d16786b6b,a39c1aef80bd5e38c36165725e9338c841aee28b3df20c7ef51a4ffe884fcba5,ef97182e7bc8bcfd1498a5f5abae70234d4a3cad1ae3ed150e758d05ee81c2dc,1e05055e50586d47341a775903f017ab6f387c304aedc391a0e991d4568f1638
message_id,<2399966.1075843964095.JavaMail.evans@thyme>,<13101411.1075856386039.JavaMail.evans@thyme>,<27554050.1075857540056.JavaMail.evans@thyme>,<5020107.1075845563725.JavaMail.evans@thyme>,<17320932.1075857683948.JavaMail.evans@thyme>,<25204828.1075844548975.JavaMail.evans@thyme>,<14886018.1075844549091.JavaMail.evans@thyme>,<27396355.1075844511918.JavaMail.evans@thyme>,<24861977.1075858950944.JavaMail.evans@thyme>,<15543318.1075844952459.JavaMail.evans@thyme>,...,<25517044.1075844812913.JavaMail.evans@thyme>,<6448441.1075859075339.JavaMail.evans@thyme>,<27321259.1075859077694.JavaMail.evans@thyme>,<22194030.1075860930220.JavaMail.evans@thyme>,<29744411.1075860930444.JavaMail.evans@thyme>,<16421444.1075853787851.JavaMail.evans@thyme>,<870058.1075853780081.JavaMail.evans@thyme>,<30120365.1075853236037.JavaMail.evans@thyme>,<11626193.1075843157150.JavaMail.evans@thyme>,<1815387.1075840095926.JavaMail.evans@thyme>
date,2001-01-03 10:15:00+00:00,2001-01-03 10:28:00+00:00,2001-01-03 11:28:00+00:00,2001-01-03 13:11:00+00:00,2001-01-04 01:11:00+00:00,2000-04-25 18:53:00+00:00,2000-04-26 13:37:00+00:00,2000-04-26 14:24:00+00:00,2001-09-25 18:08:56+00:00,2000-07-07 09:44:00+00:00,...,2001-03-16 10:29:00+00:00,2001-12-06 16:02:08+00:00,2001-12-07 15:10:57+00:00,2001-12-10 03:22:43+00:00,2001-12-10 21:38:55+00:00,2000-10-26 10:58:00+00:00,2000-10-26 11:21:00+00:00,2001-03-07 11:41:00+00:00,2000-11-22 15:03:00+00:00,2000-12-13 15:58:00+00:00
sender,cathy.phillips@enron.com,vince.kaminski@enron.com,jeffrey.shankman@enron.com,kimberly.hillis@enron.com,john.lavorato@enron.com,sara.shackleton@enron.com,sara.shackleton@enron.com,tanya.rohauer@enron.com,mark.greenberg@enron.com,dana.gibbs@enron.com,...,larry.hunter@enron.com,bill.rapp@enron.com,mark.mcconnell@enron.com,gregory.porter@enron.com,mary.darveaux@enron.com,chris.germany@enron.com,jeffrey.porter@enron.com,susan.mara@enron.com,susan.mara@enron.com,karen.denne@enron.com
to,charlene.jackson@enron.com,charlene.jackson@enron.com,jennifer.burns@enron.com,charlene.jackson@enron.com,charlene.jackson@enron.com,jeff.nogid@enron.com,"rod.nelson@enron.com, tanya.rohauer@enron.com",sara.shackleton@enron.com,michael.bridges@enron.com,stanley.horton@enron.com,...,sara.shackleton@enron.com,"steven.harris@enron.com, kimberly.watson@enron.com, michelle.lokay@enron.com, \n\tmark.mcconnell@enron.com, robert.kilmer@enron.com, \n\tteb.lokey@enron.com, kay.miller@enron.com, steve.kirk@enron.com, \n\tperry.frazier@enron.com, joe.hartsoe@enron.com","bill.rapp@enron.com, steven.harris@enron.com, kimberly.watson@enron.com, \n\tmichelle.lokay@enron.com, robert.kilmer@enron.com, \n\tteb.lokey@enron.com, kay.miller@enron.com, steve.kirk@enron.com, \n\tperry.frazier@enron.com, joe.hartsoe@enron.com","bill.rapp@enron.com, steven.harris@enron.com, kimberly.watson@enron.com, \n\tmichelle.lokay@enron.com, mark.mcconnell@enron.com, \n\trobert.kilmer@enron.com, teb.lokey@enron.com, kay.miller@enron.com, \n\tsteve.kirk@enron.com, perry.frazier@enron.com, joe.hartsoe@enron.com","bill.rapp@enron.com, kimberly.watson@enron.com, michelle.lokay@enron.com, \n\tmark.mcconnell@enron.com","dave.scott@enron.com, jeffrey.porter@enron.com, victoria.versen@enron.com",chris.germany@enron.com,"karen.denne@enron.com, mark.palmer@enron.com, richard.shapiro@enron.com, \n\tjames.steffes@enron.com, jeff.dasovich@enron.com, \n\tpaul.kaufman@enron.com, sandra.mccubbin@enron.com, \n\tkathryn.corbally@enron.com, fergus@brobeck.com, \n\trichard.sanders@enron.com, rcarroll@bracepatt.com, \n\tdwatkiss@bracepatt.com, mary.hain@enron.com, alan.comnes@enron.com, \n\tchristian.yoder@enron.com","jeff.dasovich@enron.com, steven.kean@enron.com, richard.shapiro@enron.com, \n\tjames.steffes@enron.com, harry.kingerski@enron.com, \n\tmona.petrochko@enron.com, paul.kaufman@enron.com, \n\tsandra.mccubbin@enron.com","kenneth.lay@enron.com, jeff.skilling@enron.com, cliff.baxter@enron.com, \n\trex.rogers@enron.com, james.derrick@enron.com, mark.koenig@enron.com, \n\tpaula.rieker@enron.com, mark.metts@enron.com, \n\tlance.schuler-legal@enron.com, diane.bazelides@enron.com, \n\tsteven.kean@enron.com"
cc,,shirley.crenshaw@enron.com,,,,,,,"['tana.jones@enron.com', 'c..koehler@enron.com']",,...,,"['gregory.porter@enron.com', 'maria.pavlou@enron.com']","['gregory.porter@enron.com', 'maria.pavlou@enron.com']",maria.pavlou@enron.com,"['steve.kirk@enron.com', 'steven.harris@enron.com']",,"['dave.scott@enron.com', 'victoria.versen@enron.com']",,,mark.palmer@enron.com
bcc,,shirley.crenshaw@enron.com,,,,,,,"tana.jones@enron.com, c..koehler@enron.com",,...,,"gregory.porter@enron.com, maria.pavlou@enron.com","gregory.porter@enron.com, maria.pavlou@enron.com",maria.pavlou@enron.com,"steve.kirk@enron.com, steven.harris@enron.com",,"dave.scott@enron.com, victoria.versen@enron.com",,,mark.palmer@enron.com
subject,associate and analyst programs new year s kickoff reception,associate and analyst programs new year s kickoff reception,associate and analyst programs new year s kickoff reception,associate and analyst programs new year s kickoff reception,associate and analyst programs new year s kickoff reception,j p morgan isda,j p morgan isda,j p morgan isda,deloitte agreement,s 1,...,merrill,transwestern response to ferc data request usgt negotiated rate filing,transwestern response to ferc data request usgt negotiated rate filing,transwestern response to ferc data request usgt negotiated rate filing,transwestern response to ferc data request usgt negotiated rate filing,daily volumes for 10 26 and 10 27,daily volumes for 10 26 and 10 27,cpuc filing enron not mentioned in cartel,iep info on governor s meeting mon 11 27 want pre meeting at noon,azurix release
body,re associate and analyst programs new year s kickoff reception hi charlene is this a different reception from the one we have on mike mcconnell s calendar for january 16th unfortunately mike will be at an off site meeting on the 11th and i do not know if he can make it back in time for a 4 30 reception thanks cathy p x 36898 enron north america corp from charlene jackson enron 01 03 2001 10 08 am sent by cheryl kuehl enron,re associate and analyst programs new year s kickoff reception thanks for the invitation i shall attend vince kaminski enron north america corp from charlene jackson enron 01 03 2001 10 08 am sent by cheryl kuehl enron,please put on calendar forwarded by jeffrey a shankman hou ect on 01 03 2001 11 30 am enron north america corp from charlene jackson enron 01 03 2001 10 08 am sent by cheryl kuehl enron,re associate and analyst programs new year s kickoff reception charlene thank you for the invitiation however i wanted to let you know that john is currently scheduled to be out of the country on january 11 i have added it to his schedule incase his plans change kim from charlene jackson 01 03 2001 10 08 am sent by cheryl kuehl,re associate and analyst programs new year s kickoff reception charlene thank you for the invitiation however i wanted to let you know that john is currently scheduled to be out of the country on january 11 i have added it to his schedule incase his plans change kim from charlene jackson 01 03 2001 10 08 am sent by cheryl kuehl,j p morgan isda jeff i have not heard a word from credit who did you speak with please let me know and i will follow up thanks sara,rod and tanya please let me know who is handling so i can pass on the news to jeff thanks sara forwarded by sara shackleton hou ect on 04 26 2000 02 34 pm enron global finance from jeff nogid 04 26 2000 09 18 am,sara what is this about jeff s message is a bit vague sara shackleton 04 26 2000 01 37 pm,deloitte agreement michael i have attached below a revised version of the channel marketing agreement with deloitte this document is the most current form of agreement that needs to be used for these deals and also reflects my comments these comments are based upon the comments submitted by deloitte i have incorporated those that we discussed and made some additional comments you will note that in the fee payment section i have included the present value concept that you requested i have not however defined this concept but would assert that it should be defined in the agreement accordingly please let me know how you want to define it as i indicated above this is a bit of a different form than the one you submitted to deloitte for review so that we can ensure that accurate documents are distributed please allow us to prepare the drafts for distribution to potential channel marketing partners like the preparation of nda s this will enable the legal dept to keep track of the agreement and ensure the right version is used please let me know if you should need anything further mark,for your information dana forwarded by dana gibbs houston eott on 07 07 00 09 33 am baird bob rbaird velaw com 07 06 00 09 40 pm,...,fyi forwarded by larry joe hunter hou ect on 03 16 2001 10 28 am from larry joe hunter 03 16 2001 10 28 am,transwestern response to ferc data request usgt negotiated rate filing attached for your review and comments is a draft of tw s response to the ferc data request in the usgt negotiated rate proceeding please note that our response to data request no 1 contemplates that we will provide to ferc copies of the other bids that were received on this capacity we could attempt to summarize this other bids but i think the better approach is to just provide copies a schedule of actual volumes transported and actual rates charged usgt is attached this is the schedule c that is referenced in our response to data request no 4 this will need to be updated next week prior to filing i do not have the other attachments to the responses in electronic format i can of course provide paper copies of these to anyone who would like to see them i would appreciate receiving any comments by noon on monday december 10 thanks,re transwestern response to ferc data request usgt negotiated rate filing bill i took out the formulas of the worksheet and left only the figures for the calculation for the rates of the alternate deliveries in december mark,re transwestern response to ferc data request usgt negotiated rate filing these look good greg,re transwestern response to ferc data request usgt negotiated rate filing i am not sure who prepared the detail schedule for data request no 4 but we have a few questions the letter agreement dated 2 6 2001 effective november 1 2001 states 1 primary points east to east flow rate equals 0 025 demand rate and a maximum commodity rate which is 0 0147 inclusive of surcharges why does the schedule have 0 0092 as the primary path rate also since the question asks for the transportation charged we thought we would add the demand rate and the associated mdq 2 alternate points east to west flow rate equals negotiated rate but in no event shall the resultant commodity be less than 0 0246 mmbtu why does the schedule have a rate of 0 0245 mmbtu,re daily volumes for 10 26 and 10 27 maybe we should add another section to mr scott s worksheet for third party buy s and sells like the aquilla deal 452810 and the deal we did on the 7th where ena bought the gas back from new power not a big deal for october but we will probably start doing our maunal billing process again for the winter months i could see you guys buying incremental third party gas that we may need to schedule especially during high pipeline constraints example you might buy gas from sempra at eagle into cgas and we use your transport to get it to a citygate ena would buy it from new power at eagel and sell it back to new power at the citygate we should let you know what the deal ticket number is via email or phone call and scott could put it on the worksheet so if we had this tab for october it would just have 2 deals on it so far comments,sounds ok to us look for a change in our format chris germany ect 10 26 2000 10 58 am,cpuc filing enron not mentioned in cartel sue mara enron corp tel 415 782 7802 fax 415 782 7854 forwarded by susan j mara na enron on 03 07 2001 09 37 am 09 daniel douglass douglass arterhadden com 0903 07 2001 08 40 am 09 09 20 09 09,iep info on governor s meeting mon 11 27 want pre meeting at noon forwarded by susan j mara na enron on 11 22 2000 12 51 pm chudson carol iepa com 11 22 2000 12 47 pm,azurix release attached for your review and approval are the press release announcing the merger plan with azurix and a q a document both have been approved by mark metts and lance schuler pending signature of the merger agreement tonight we plan to release concurrently with azurix before the market opens tomorrow morning if you have any comments or changes please call mark palmer at x34738 before 6 a m tomorrow thank you karen
x_from,Cathy Phillips,Vince J Kaminski,Jeffrey A Shankman,Kimberly Hillis,John J Lavorato,Sara Shackleton,Sara Shackleton,Tanya Rohauer,"Greenberg, Mark </O=ENRON/OU=NA/CN=RECIPIENTS/CN=MGREENBE>",Dana Gibbs,...,Larry Joe Hunter,"Rapp, Bill </O=ENRON/OU=NA/CN=RECIPIENTS/CN=BRAPP>","McConnell, Mark </O=ENRON/OU=NA/CN=RECIPIENTS/CN=MMCCONNE>","Porter, J. Gregory </O=ENRON/OU=NA/CN=RECIPIENTS/CN=GPORTER>","Darveaux, Mary </O=ENRON/OU=NA/CN=RECIPIENTS/CN=MDARVEA>",Chris Germany,Jeffrey Porter,Susan J Mara,Susan J Mara,Karen Denne
x_to,Charlene Jackson,Charlene Jackson,Jennifer Burns,Charlene Jackson,"Jackson, Charlene </o=ENRON/ou=NA/cn=Recipients/cn=Notesaddr/cn=2c9026cf-c82ecc89-86256802-5258d5>",Jeff Nogid,"Rod Nelson, Tanya Rohauer",Sara Shackleton,"Bridges, Michael </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Mbridge2>",Stanley Horton,...,Sara Shackleton,"Harris, Steven </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Sharris1>, Watson, Kimberly </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Kwatson>, Lokay, Michelle </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Mlokay>, McConnell, Mark </O=ENRON/OU=NA/CN=RECIPIENTS/CN=MMcConne>, Kilmer III, Robert </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Rkilmer>, Lokey, Teb </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Tlokey>, Miller, Mary Kay </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Mkmiller>, Kirk, Steve </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Skirk>, Frazier, Perry </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Pfrazier>, Hartsoe, Joe </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Jhartso>","Rapp, Bill </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Brapp>, Harris, Steven </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Sharris1>, Watson, Kimberly </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Kwatson>, Lokay, Michelle </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Mlokay>, Kilmer III, Robert </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Rkilmer>, Lokey, Teb </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Tlokey>, Miller, Mary Kay </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Mkmiller>, Kirk, Steve </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Skirk>, Frazier, Perry </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Pfrazier>, Hartsoe, Joe </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Jhartso>","Rapp, Bill </O=ENRON/OU=NA/CN=RECIPIENTS/CN=BRAPP>, Harris, Steven </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Sharris1>, Watson, Kimberly </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Kwatson>, Lokay, Michelle </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Mlokay>, McConnell, Mark </O=ENRON/OU=NA/CN=RECIPIENTS/CN=MMcConne>, Kilmer III, Robert </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Rkilmer>, Lokey, Teb </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Tlokey>, Miller, Mary Kay </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Mkmiller>, Kirk, Steve </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Skirk>, Frazier, Perry </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Pfrazier>, Hartsoe, Joe </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Jhartso>","Rapp, Bill </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Brapp>, Watson, Kimberly </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Kwatson>, Lokay, Michelle </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Mlokay>, McConnell, Mark </O=ENRON/OU=NA/CN=RECIPIENTS/CN=MMcConne>","Dave Scott, Jeffrey Porter, Victoria Versen",Chris Germany,"Karen Denne, Mark Palmer, Richard Shapiro, James D Steffes, Jeff Dasovich, Paul Kaufman, Sandra McCubbin, Kathryn Corbally, fergus@brobeck.com, Richard B Sanders, rcarroll@bracepatt.com, dwatkiss@bracepatt.com, Mary Hain, Alan Comnes, Christian Yoder","Jeff Dasovich, Steven J Kean, Richard Shapiro, James D Steffes, Harry Kingerski, Mona L Petrochko, Paul Kaufman, Sandra McCubbin","Kenneth Lay, Jeff Skilling, Cliff Baxter, Rex Rogers, James Derrick, Mark Koenig, Paula Rieker, Mark Metts, Lance Schuler-Legal, Diane Bazelides, Steven J Kean"
x_cc,,Shirley Crenshaw,,,,,,,"Jones, Tana </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Tjones>, Koehler, Anne C. </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Akoehle>",,...,,"Porter, J. Gregory </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Gporter>, Pavlou, Maria </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Mpavlou>","Porter, J. Gregory </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Gporter>, Pavlou, Maria </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Mpavlou>","Pavlou, Maria </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Mpavlou>","Kirk, Steve </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Skirk>, Harris, Steven </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Sharris1>",,"Dave Scott, Victoria Versen",,,Mark Palmer
x_bcc,,,,,,,,,,,...,,,,,,,,,,
x_folder,\Mark_McConnell_June2001\Notes Folders\Sent,\Vincent_Kaminski_Jun2001_2\Notes Folders\Discussion threads,\Jeffrey_Shankman_Jun2001\Notes Folders\Discussion threads,\John_Lavorato_Oct2001\Notes Folders\Sent,\jlavora\Sent Items,\Sara_Shackleton_Dec2000_June2001_1\Notes Folders\Sent,\Sara_Shackleton_Dec2000_June2001_1\Notes Folders\Sent,\Sara_Shackleton_Dec2000_June2001_1\Notes Folders\Notes inbox,"\TJONES (Non-Privileged)\Jones, Tana\Inbox",\Stanley_Horton_1\Notes Folders\Discussion threads,...,\Sara_Shackleton_Dec2000_June2001_2\Notes Folders\Notes inbox,"\Bill_Rapp_Jan2002\Rapp, Bill\Sent Items","\Bill_Rapp_Jan2002\Rapp, Bill\Inbox","\Kim_Watson_Mar2002\Watson, Kimberly\Inbox","\Kim_Watson_Mar2002\Watson, Kimberly\Inbox",\Chris_Germany_Dec2000\Notes Folders\Sent,\Chris_Germany_Dec2000\Notes Folders\New power,\Richard_Sanders_Oct2001\Notes Folders\Iso_ pricecaps,\Jeff_Dasovich_Dec2000\Notes Folders\Notes inbox,\Jeffrey_Skilling_Dec2000\Notes Folders\Notes inbox
x_origin,MCCONNELL-M,Kaminski-V,Shankman-J,LAVORATO-J,Lavorado-J,SHACKLETON-S,SHACKLETON-S,SHACKLETON-S,Jones-T,HORTON-S,...,SHACKLETON-S,Rapp-B,Rapp-B,Watson-K,Watson-K,Germany-C,Germany-C,Sanders-R,DASOVICH-J,SKILLING-J
x_filename,mmcconn.nsf,vkamins.nsf,jshankm.nsf,jlavora.nsf,jlavora.pst,sshackle.nsf,sshackle.nsf,sshackle.nsf,TJONES (Non-Privileged).pst,shorton.nsf,...,sshackle.nsf,brapp (Non-Privileged).pst,brapp (Non-Privileged).pst,kwatson (Non-Privileged).pst,kwatson (Non-Privileged).pst,cgerman.nsf,cgerman.nsf,rsanders.nsf,jdasovic.nsf,jskillin.nsf

In [25]:
data[data['id'].duplicated]

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [64]:
data[data['id'].duplicated(keep=False)].groupby(['id'])['sender'].nunique().sort_values(ascending=False).head(10)

id
93055480c9cb9334ba759fe3111cb3f6da88507606c10474885c5d29ce17d3d6    21
01f7e3ee5d5086792309a060a83ff67b6e5abdf57c3b8147c87c6a5c98263dbc     8
7816d80fb0307199545e0675c62045ef539680d4d38e7c66f5f58ba43320a76a     4
4caec6c9dee1378c5fa91c748ced741c530e30985718262ac273e1d757dfe1a1     4
5cbeb7631365f7c8b58cd15679a7671da60eb2a81d19d55ceb08f60a9cb4bd27     4
675ee824e1004087b5f1b991a933080090af34a41917ef9692354be6b131d4a4     3
00b1be07dfa5d170df87af67414f8969d228b9c593bc1520ea79ac7e836826d7     3
7ca073df58d764a804146619a52d91c6e0781c51fe6ab134b0b40dc02ed20b6a     3
5c959a701435d26e7f02484fe15dfdb56a07756bfe69a42d10dca67fab215fcd     3
74265b029aef807980de45f55aa4cf0caaf49d139691639a63c78885cf3a3bd2     3
Name: sender, dtype: int64

In [69]:
data[data["subject"].str.contains("enron's secrets revealed", case=False, na=False)]

,id,message_id,date,sender,to,cc,bcc,subject,body,x_from,x_to,x_cc,x_bcc,x_folder,x_origin,x_filename,source_file
13228,465c2c46a17dbee91ebc632b5b0a0c4fc22b3d3a012f98828a72b1184c04de1b,<17413604.1075852531433.JavaMail.evans@thyme>,"Wed, 8 Aug 2001 14:46:38 -0700 (PDT)",john.hogan@mirant.com,jtholt@enron.com,,,FW: Enron's Secrets Revealed,FW: Enron's Secrets Revealed Whew! Now we can all be successful as ENE!!!! To: john.hogan@southernenergy.com,"""Hogan, John"" <john.hogan@mirant.com>@ENRON <IMCEANOTES-+22Hogan+2C+20John+22+20+3Cjohn+2Ehogan+40mirant+2Ecom+3E+40ENRON@ENRON.com>",'jtholt@enron.com',None,None,"\JTHOLT (Non-Privileged)\Tholt, Jane M.\JANIE",Tholt-J,JTHOLT (Non-Privileged).pst,Enron Data
13254,03a56165c7c8f8710e70e6666b24479fd60e6ceb75c09a01e7c74d913d6d5226,<25150000.1075852531504.JavaMail.evans@thyme>,"Thu, 9 Aug 2001 10:08:41 -0700 (PDT)",sbaird@socalgas.com,m..tholt@enron.com,,,RE: Enron's Secrets Revealed,RE: Enron's Secrets Revealed Could you send me a copy? To: sbaird@socalgas.com,"""Baird, Steven L. - TP6SLB"" <SBaird@socalgas.com>@ENRON <IMCEANOTES-+22Baird+2C+20Steven+20L+2E+20-+20TP6SLB+22+20+3CSBaird+40socalgas+2Ecom+3E+40ENRON@ENRON.com>","Tholt, Jane M. </O=ENRON/OU=NA/CN=RECIPIENTS/CN=JTHOLT>",None,None,"\JTHOLT (Non-Privileged)\Tholt, Jane M.\JANIE",Tholt-J,JTHOLT (Non-Privileged).pst,Enron Data
66369,22b6765f11caab8b90d997a824ce742519c1ac18aed40c777116e8f862a182db,<27117893.1075862293714.JavaMail.evans@thyme>,"Sat, 28 Jul 2001 11:05:58 -0700 (PDT)",pfusaro@nirvanasoft.com,tumphrey@energyatlantic.com,,,Enron's Secrets Revealed,"Enron's Secrets Revealed How has Enron managed to achieve such success while other energy firms have struggled to deal with the changing market landscape? Global Change Associates is pleased to announce the publication of a new corporate profile entitled, ""Enron 2001: An Inside View"". This objective study takes an insider's look at Enron, specifically, how the firm operates and the keys to its success. Much of the information provided comes from first hand accounts and covers areas such as: The firm's structure and operations The recruitment and training of new employees How Enron empowers and compensates its employees The keys to structuring Enron type ""risk free"" transactions How to negotiate with Enron Why Enron occasionally forgives counterparty obligations Is the Enron model right for your organization? Enron 2001: An Inside View is a unique publication. It provides valuable insight into the firm's operations and analyzes its successes and failures. For those firms dealing directly with Enron, or thinking about adopting some of Enron's business practices, it is an invaluable, must have tool. This innovative study is available for purchase at $995.00. For a detailed Table of Contents please open the attached file, Enron2001TOC. To order please go to <URL> click on ""Reports"" or complete the attached order form and fax to 212-625-8810. For more information on this product please contact Alan M. Herbst at 212-625-1711 or via email at info@global-change.com. To be removed from this distribution list, please reply with the word REMOVE in the subject line.",Global Change Associates <pfusaro@nirvanasoft.com>,tumphrey@energyatlantic.com,None,None,"\RHAYSLE (Non-Privileged)\Hayslett, Rod\Projects",Hayslett-R,RHAYSLE (Non-Privileged).pst,Enron Data
66401,22b6765f11caab8b90d997a824ce742519c1ac18aed40c777116e8f862a182db,<32233043.1075862297204.JavaMail.evans@thyme>,"Thu, 16 Aug 2001 05:24:13 -0700 (PDT)",tdouek@nirvanasoft.com,rod.hayslett@enron.com,,,Enron's Secrets Revealed,"Enron's Secrets Revealed How has Enron managed to achieve such success while other energy firms have struggled to deal with the changing market landscape? Global Change Associates is pleased to announce the publication of a new corporate profile entitled, ""Enron 2001: An Inside View"". This objective study takes an insider's look at Enron, specifically, how the firm operates and the keys to its success. Much of the information provided comes from first hand accounts and covers areas such as: The firm's structure and operations The recruitment and training of new employees How Enron empowers and compensates its employees The keys to structuring Enron type ""risk free"" transactions How to negotiate with Enron Why Enron occasionally forgives counterparty obligations Is the Enron model right for your organization? Enron 2001: An Inside View is a unique publication. It provides valuable insight into the firm's operations and analyzes its successes and failures. For those firms dealing directly with Enron, or thinking about adopting some of Enron's business practices, it is an invaluable, must have tool. This innovative study is available for purchase at $995.00. For a detailed Table of Contents please open the attached file, Enron2001TOC. To order please go to <URL> click on ""Reports"" or complete the attached order form and fax to 212-625-8810. For more information on this product please contact Alan M. Herbst at 212-625-1711 or via email at info@global-change.com. To be removed from this distribution list, please reply with the word REMOVE in the subject line.",Global Change Associates <tdouek@nirvanasoft.com>,"Hayslett, Rod </O=ENRON/OU=NA/CN=RECIPIENTS/CN=RHAYSLE>",None,None,"\RHAYSLE (Non-Privileged)\Hayslett, Rod\Projects\Hold",Hayslett-R,RHAYSLE (Non-Privileged).pst,Enron Data
89145,10b3233ea2d6d232c845ed88521fd079af797cce5346f0f944e10768d89ab373,<1051256.1075863370465.JavaMail.evans@thyme>,"Thu, 30 Aug 2001 14:07:38 -0700 (PDT)",mark.ruane@enron.com,rick.buy@enron.com,,,FW: Enron's Secrets Revealed - 8/27/01,"Should we buy a copy? Apparently this is quite detailed on how to push deals through the system. To: Bonney, Mark","Ruane, Mark </O=ENRON/OU=NA/CN=RECIPIENTS/CN=MRUANE>","Buy, Rick </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Rbuy>",None,None,"\RBUY (Non-Privileged)\Buy, Rick\Inbox",Buy-R,RBUY (Non-Privileged).pst,Enron Data
91242,b177dfbbda13c868a9b14a35fe6676ea9a59f20e08a2623c44cd2a8a6358aa4b,<15665559.1075852538759.JavaMail.evans@thyme>,"Thu, 9 Aug 2001 09:56:20 -0700 (PDT)",m..tholt@enron.com,sbaird@socalgas.com,,,FW: Enron's Secrets Revealed,To: 'jtholt@enron.com',"Tholt, Jane M. </O=ENRON/OU=NA/CN=RECIPIENTS/CN=JTHOLT>",'sbaird@socalgas.com',None,None,"\JTHOLT (Non-Privileged)\Tholt, Jane M.\Sent Items",Tholt-J,JTHOLT (Non-Privileged).pst,Enron Data
91334,00e0a5017b69105e73bc28fd1b60331373606538ae95461b82d9572e6fcfab36,<24321870.1075852538637.JavaMail.evans@thyme>,"Thu, 9 Aug 2001 05:21:19 -0700 (PDT)",m..tholt@enron.com,k..allen@enron.com,,,FW: Enron's Secrets Revealed,We'll do anything to try to make a buck. To: 'jtholt@enron.com',"Tholt, Jane M. </O=ENRON/OU=NA/CN=RECIPIENTS/CN=JTHOLT>","Allen, Phillip K. </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Pallen>",None,None,"\JTHOLT (Non-Privileged)\Tholt, Jane M.\Sent Items",Tholt-J,JTHOLT (Non-Privileged).pst,Enron Data
128287,e6ce0275ba793e5b27e8baf67978a5e0e82f3ae08f57372b6aa9efab7380934d,<12589394.1075849383206.JavaMail.evans@thyme>,"Mon, 30 Jul 2001 04:47:00 -0700 (PDT)",susan.mara@enron.com,"karen.denne@enron.com, mark.palmer@enron.com, jeff.dasovich@enron.com, \n\trichard.shapiro@enron.com, james.steffes@enron.com, \n\tharry.kingerski@enron.com, paul.kaufman@enron.com",,,Fw: Enron's Secrets Revealed,"Shall we buy this? Sue Mara Enron Corp. Tel: (415) 782-7802 Fax:(415) 782-7854 Forwarded by Susan J Mara/NA/Enron on 07/30/2001 09:44 AM ""Dan Douglass"" <douglass@energyattorney.com> 07/30/2001 08:38 AM",Susan J Mara,"Karen Denne, Mark Palmer, Jeff Dasovich, David Leboe/Enron@EnronXGate, Richard Shapiro, James D Steffes, Harry Kingerski, Paul Kaufman",None,None,\Jeff_Dasovich_Oct2001\Notes Folders\Notes inbox,DASOVICH-J,jdasovic.nsf,Enron Data
137746,a964b2555863df1bd578455b58437162977062fa2cc037875a2d32eee216714b,<33425331.1075849618313.JavaMail.evans@thyme>,"Mon, 30 Jul 2001 04:54:00 -0700 (PDT)",jeff.dasovich@enron.com,"eldon@direcpc.com, nancy.sellers@robertmondavi.com, \n\tpsellers@haas.berkeley.edu, cameron@perfect.com",,,Fw: Enron's Secrets Revealed,"Fw: Enron's Secrets Revealed Jeez, this takes the cake. Cameron, Perfect may want to get the publication! Best, Jeff Original Message Sent: Friday, July 27, 2001 9:13 PM",Jeff Dasovich,"eldon@direcpc.com, Nancy.Sellers@RobertMondavi.com, psellers@Haas.Berkeley.EDU, Cameron Sellers <cameron@perfect.com> @ ENRON",None,None,\Jeff_Dasovich_Oct2001\Notes Folders\Sent,DASOVICH-J,jdasovic.nsf,Enron Data
141819,e6ce0275ba793e5b27e8baf67978a5e0e82f3ae08f57372b6aa9efab7380934d,<27105640.1075849347930.JavaMail.evans@thyme>,"Mon, 30 Jul 2001 04:47:00 -0700 (PDT)",susan.mara@enron.com,"karen.denne@enron.com, mark.palmer@enron.com, jeff.dasovich@enron.com, \n\trichard.shapiro@enron.com, james.steffes@enron.com, \n\tharry.kingerski@enron.com, paul.kaufman@enron.com",,,Fw: Enron's Secrets Revealed,"Shall we buy this? Sue Mara Enron Corp. Tel: (415) 782-7802 Fax:(415) 782-7854 Forwarded by Susan J Mara/NA/Enron on 07/30/2001 09:44 AM ""Dan Douglass"" <douglass@energyattorney.com> 07/30/2001 08:38 AM",Susan J Mara,"Karen Denne, Mark Palmer, Jeff Dasovich, David Leboe/Enron@EnronXGate, Richard Shapiro, James D Steffes, Harry Kingerski, Paul Kaufman",None,None,\Jeff_Dasovich_Oct2001\Notes Folders\All documents,DASOVICH-J,jdasovic.nsf,Enron Data
146316,a964b2555863df1bd578455b58437162977062fa2cc037875a2d32eee216714b,<11540808.1075849347996.JavaMail.evans@thyme>,"Mon, 30 Jul 2001 04:54:00 -0700 (PDT)",jeff.dasovich@enron.com,"eldon@direcpc.com, nancy.sellers@robertmondavi.com, \n\tpsellers@haas.berkeley.edu, cameron@perfect.com",,,Fw: Enron's Secrets Revealed,"Fw: Enron's Secrets Revealed Jeez, this takes the cake. Cameron, Perfect may want to get the publication! Best, Jeff Original Message Sent: Friday, July 27, 2001 9:13 PM",Jeff Dasovich,"eldon@direcpc.com, Nancy.Sellers@RobertMondavi.com, psellers@Haas.Berkeley.EDU, Cameron Sellers <cameron@perfect.com> @ ENRON",None,None,\Jeff_Dasovich_Oct2001\Notes Folders\All documents,DASOVICH-J,jdasovic.nsf,Enron Data
164708,544c335081490ac0aaab2f88cc490b458155f075aad28ba47a3808c481ed12d3,<16766046.1075862102799.JavaMail.evans@thyme>,"Thu, 4 Oct 2001 12:03:07 -0700 (PDT)",trevor.woods@enron.com,"john.massey@enron.com, kevin.mcgowan@enron.com, lenny.hochschild@enron.com, \n\te.taylor@enron.com, aaron.martinsen@enron.com, \n\tderek.wilson@enron.com, mark.friedman@enron.com, \n\tmarc.wharton@enron.com, chad.pennix@enron.com",,,FW: Enron's Secrets Revealed! fyi,"FW: Enron's Secrets Revealed! fyi Sent: Wednesday, October 03, 2001 4:33 PM","Woods, Trevor </O=ENRON/OU=NA/CN=RECIPIENTS/CN=TWOODS>","Massey II, John </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Jmassey>, Mcgowan, Kevin </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Kmcgowa>, Hochschild, Lenny </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Lhochsch>, Taylor, Michael E </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Mtaylor5>, Martinsen, Aaron </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Amarti10>, Wilson, Derek </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Dwilson4>, Friedman, Mark </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Mfriedm>, Wharton, Marc </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Mwharton>, Pennix, Chad </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Jpennix>",None,None,"\MTAYLOR5 (Non-Privileged)\Taylor, Michael E\Inbox\Social",Taylor-M,MTAYLOR5 (Non-Privileged).pst,Enron Data
204236,45d12d6907a6ce1446ac56255e19f7db73ea2330c72cfd9afbeec5fc85d98a06,<31083586.1075853019810.JavaMail.evans@thyme>,"Thu, 4 Oct 2001 09:00:18 -0700 (PDT)",louise.kitchen@enron.com,f..calger@enron.com,,,RE: Enron's Secrets Revealed!,"RE: Enron's Secrets Revealed! Itss crap almost all of our own websites. I've read it probably have a copy somewhere if you want it. To: Kitchen, Louise","Kitchen, Louise </O=ENRON/OU=NA/CN=RECIPIENTS/CN=LKITCHEN>","Calger, Christopher F. </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Ccalger>",None,None,\LKITCHEN (Non-Privileged)\Sent Items,Kitchen-L,LKITCHEN (Non-Privileged).pst,Enron Data
206086,246b59f5230689fec25d7223d336777a02faaf6883ca38981c514817a6583c8f,<10202.1075840887471.JavaMail.evans@thyme>,"Thu, 4 Oct 2001 08:32:39 -0700 (PDT)",f..calger@enron.com,louise.kitchen@enron.com,,,Enron's Secrets Revealed!,"This is kind of weird and flattering, but it makes me wonder how they got this info and if we care. Chris Calger 503-464-3735 To: Calger, Christopher F.","Calger, Christopher F. </O=ENRON/OU=NA/CN=RECIPIENTS/CN=CCALGER>","Kitchen, Louise </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Lkitchen>",None,None,"\ExMerge - Kitchen, Louise\'Americas\Portland",KITCHEN-L,louise kitchen 2-7-02.pst,Enron Data
206750,3714416dcbd19011d876cb3bdfc0d46ce9aa2ffac34b8bb8f83dad5eb8bed504,<7666034.1075852999054.JavaMail.evans@thyme>,"Tue, 31 Jul 2001 12:49:07 -0700 (PDT)",karen.denne@enron.com,louise.kitchen@enron.com,,,FW: Enron's Secrets Revealed,"To: Denne, Karen; Armogida, Jim","Denne, Karen </O=ENRON/OU=NA/CN=RECIPIENTS/CN=KDENNE>","Kitchen, Louise </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Lkitchen>",None,None,\LKITCHEN (Non-Privileged)\'Americas\OOC,Kitchen-L,LKITCHEN (Non-Privileged).pst,Enron Data
208113,3714416dcbd19011d876cb3bdfc0d46ce9aa2ffac34b8bb8f83dad5eb8bed504,<20953732.1075840874092.JavaMail.evans@thyme>,"Tue, 31 Jul 2001 12:49:07 -0700 (PDT)",karen.denne@enron.com,louise.kitchen@enron.com,,,FW: Enron's Secrets Revealed,"To: Denne, Karen; Armogida, Jim","Denne, Karen </O=ENRON/OU=NA/CN=RECIPIENTS/CN=KDENNE>","Kitchen, Louise </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Lkitchen>",None,None,"\ExMerge - Kitchen, Louise\'Americas\Mrha\OOC",KITCHEN-L,louise kitchen 2-7-02.pst,Enron Data
298984,63da37520a2f0a9e3a992886306e9b649b327045a9e819c58f3406b0ccc1a7a9,<19415955.1075862297033.JavaMail.evans@thyme>,"Mon, 30 Jul 2001 09:45:22 -0700 (PDT)",rod.hayslett@enron.com,"stanley.horton@enron.com, danny.mccarty@enron.com",,,FW: Enron's Secrets Revealed,FW: Enron's Secrets Revealed FYI To: tumphrey@energyatlantic.com,"Hayslett, Rod </O=ENRON/OU=NA/CN=RECIPIENTS/CN=RHAYSLE>","Horton, Stanley </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Shorton>, McCarty, Danny </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Dmccarty>",None,None,"\RHAYSLE (Non-Privileged)\Hayslett, Rod\Projects\Hold",Hayslett-R,RHAYSLE (Non-Privileged).pst,Enron Data
300547,571cd8fb4fec12d2731a375b27f502f254feb8666078b637c3c9a4b513ec5150,<4514299.1075854933667.JavaMail.evans@thyme>,"Thu, 4 Oct 2001 11:49:23 -0700 (PDT)",alan.aronowitz@enron.com,sharon.butcher@enron.com,e..haedicke@enron.com,e..haedicke@enron.com,FW: Enron's Secrets Revealed!,"Do you know if this publication is being done with Enron's consent? Is Enron's consent necessary? Apparently, Global Change Associates is the author. One of our outside lawyers forwarded this to us yesterday. Alan To: Aronowitz, Alan; Boomer, John; Viverito, John; Robison, Michael A.; Roberson, Weezie; Del vecchio, Peter","Aronowitz, Alan </O=ENRON/OU=NA/CN=RECIPIENTS/CN=AARONOW>","Butcher, Sharon </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Sbutche>","Haedicke, Mark E. </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Mhaedic>",None,\MHAEDIC (Non-Privileged)\Deleted Items,Haedicke-M,MHAEDIC (Non-Privileged).pst,Enron Data
300598,9eb562a9a110ab0910ad13bbcb0a22c69e107f0e4ec3ae8474f18416f6bf3aa3,<25434361.1075854933511.JavaMail.evans@thyme>,"Thu, 4 Oct 2001 14:55:16 -0700 (PDT)",alan.aronowitz@enron.com,sharon.butcher@enron.com,"['e..haedicke@enron.com', 'michelle.cash@enron.com']","e..haedicke@enron.com, michelle.cash@enron.com",FW: Enron's Secrets Revealed!,Sharon: Michelle Cash indicated to me today that she was made aware of this recently and was already looking into it. Alan,"Aronowitz, Alan </O=ENRON/OU=NA/CN=RECIPIENTS/CN=AARONOW>","Butcher, Sharon </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Sbutche>","Haedicke, Mark E. </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Mhaedic>, Cash, Michelle </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Mcash>",None,\MHAEDIC (Non-Privileged)\Deleted Items,Haedicke-M,MHAEDIC (Non-Privileged).pst,Enron Data
347911,73cb61be91a213ef4da458548e9ecf9e79a28b859b6abae6bbc3c4cc7cb874c6,<1890061.1075858886723.JavaMail.evans@thyme>,"Thu, 23 Aug 2001 15:24:49 -0700 (PDT)",j..kean@enron.com,john.sherriff@enron.com,john.brindle@enron.com,john.brindle@enron.com,FW: Enron's Secrets Revealed,"I believe we have this already. John B could you send a copy to John S. To: Kean, Steven J.","Kean, Steven J. </O=ENRON/OU=NA/CN=RECIPIENTS/CN=SKEAN>","Sherriff, John </O=ENRON/OU=NA/CN=RECIPIENTS/CN=EU/cn=Recipients/cn=JSHERRIF>","Brindle, John </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Jbrindle>",None,"\SKEAN (Non-Privileged)\Kean, Steven J.\Sent Items",Kean-S,SKEAN (Non-Privileged).pst,Enron Data
370987,3534483ff89f383f5d0b877d91ec5b4132c1b77ac99f91f7b8139e9baf4c3400,<25395534.1075852429912.JavaMail.evans@thyme>,"Sun, 29 Jul 2001 04:50:39 -0700 (PDT)",chris.lenartowicz@enron.com,"juan.hernandez@enron.com, rudy.acevedo@enron.com",,,FW: Enron's Secrets Revealed,To: 'clenart@enron.com',"Lenartowicz, Chris </O=ENRON/OU=NA/CN=RECIPIENTS/CN=CLENART>","Hernandez, Juan </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Jhernan3>, Acevedo, Rudy </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Raceved>",None,None,"\JHERNAN3 (Non-Privileged)\Hernandez, Juan\Inbox",HERNANDEZ-J,JHERNAN3 (Non-Privileged).pst,Enron Data
371580,1d2947ca75dce2d2c059939b833097d1d213acd4b44870b9532c967f9def0f8c,<33005392.1075852420832.JavaMail.evans@thyme>,"Mon, 30 Jul 2001 08:47:36 -0700 (PDT)",juan.hernandez@enron.com,l..garcia@enron.com,,,FW: Enron's Secrets Revealed,"To: Hernandez, Juan; Acevedo, Rudy","Hernandez, Juan </O=ENRON/OU=NA/CN=RECIPIENTS/CN=JHERNAN3>","Garcia, Miguel L. </O=ENRON/OU=NA/CN=RECIPIENTS/CN=Mgarcia6>",None,None,"\JHERNAN3 (Non-Privileged)\Hernandez, Juan\Sent Items",HERNANDEZ-J,JHERNAN3 (Non-Privileged).pst,Enron Data

In [9]:
data.columns

Index(['Folder-User', 'Folder-Name', 'Message-ID', 'Date', 'From', 'To',
       'Subject', 'Mime-Version', 'Content-Type', 'Content-Transfer-Encoding',
       'X-From', 'X-To', 'X-cc', 'X-bcc', 'X-Folder', 'X-Origin', 'X-FileName',
       'Body', 'Cc', 'Bcc', 'Time', 'Attendees', 'Re', 'Source', 'Mail-ID',
       'POI-Present', 'Suspicious-Folders', 'Sender-Type',
       'Unique-Mails-From-Sender', 'Low-Comm', 'Contains-Reply-Forwards',
       'Label'],
      dtype='object')

In [7]:
_input = pd.read_parquet('data/enron_data_fraud_labeled.parquet', engine='pyarrow').to_dict(orient='records')

FileNotFoundError: [Errno 2] No such file or directory: 'data/enron_data_fraud_labeled.parquet'

In [6]:
data.drop(columns='Mime-Version').to_parquet('../data/enron_data_fraud_labeled.parquet', engine='pyarrow', index=False)

In [4]:
data[data['Message-ID'] == '<31789370.1075859282160.JavaMail.evans@thyme>'].T

                                                                       59584
Folder-User                                                          maildir
Folder-Name                                                       campbell-l
Message-ID                     <31789370.1075859282160.JavaMail.evans@thyme>
Date                                   Tue, 29 Dec 2020 12:53:46 -0800 (PST)
From                                                     jody421@hotmail.com
To                                  undisclosed.recipients@mailman.enron.com
Subject                                              Jennifer Lopez - Nudity
Mime-Version                                                             1.0
Content-Type                                    text/plain; charset=us-ascii
Content-Transfer-Encoding                                               7bit
X-From                                                   JODY421@hotmail.com
X-To                                Undisclosed.Recipients@mailman.enron.com
X-cc                                                                     NaN
X-bcc                                                                    NaN
X-Folder                     \Larry_Campbell_Jan2002_2\Campbell, Larry\Inbox
X-Origin                                                          Campbell-L
X-FileName                                      lcampbe (Non-Privileged).pst
Body                       Jennifer Lopez Nudity **[FULL ACCESS FREE LIFE...
Cc
Bcc
Time
Attendees
Re
Source                                                            Enron Data
Mail-ID                    46aeffeb4b4272d8a0b3ab62f4846d297a49c774c5d356...
POI-Present                                                            False
Suspicious-Folders                                                     False
Sender-Type                                                         External
Unique-Mails-From-Sender                                                 2.0
Low-Comm                                                                True
Contains-Reply-Forwards                                                False
Label                                                                      0

In [13]:
data.loc[:, 'Mail-ID'].value_counts()

data.loc[data['Mail-ID'] == '93055480c9cb9334ba759fe3111cb3f6da88507606c10474885c5d29ce17d3d6', 'Body'][419]

'Are You Living in Debt, Paycheck to Paycheck?6658 FOLLOW ME TO FINANCIAL FREEDOM!! I Am looking for people with good work ethics and extrordinary desire to earn at least $10,000 per month working from home! NO SPECIAL SKILLS OR EXPERIENCE REQUIRED. We will give you all the training and personal support you will need to ensure your success! This LEGITIMATE HOME-BASED INCOME OPPORTUNITY can put you back in control of your time, your finances, and your life! If you\'ve tried other opportunities in the past that have failed to live up their promises, THIS IS DIFFERENT THEN ANYTHING ELSE YOU\'VE SEEN! THIS IS NOT A GET RICH QUICK SCHEME! YOUR FINANCIAL PAST DOES NOT HAVE TO BE YOUR FINANCIAL FUTURE! CALL ONLY IF YOU ARE SERIOUS! 1-800-533-9351 (Free, 2 minute message) DO NOT RESPOND BY EMAIL AND DON\'T GO TO SLEEP WITHOUT LISTENING TO THIS! The moment you commit an quit holding back, all sorts of unforseen incidents, meetings and material assistance will rise up to help you. The simple act of commitment is a powerful magnet for help." Napoleon Hill To be REMOVED from this list, simply click reply and submit.'